-- Datos iniciales base
-- Depende de: create table 1.sql

-- Roles base
INSERT INTO "ROLES" ("NOMBRE_ROL", "DESCRIPCION", "NIVEL_ACCESO", "ES_SISTEMA") VALUES
('admin', 'Administrador del sistema', 100, FALSE),
('coordinador_academico', 'Coordinacion academica', 80, FALSE),
('auxiliar', 'Auxiliar administrativo', 60, FALSE),
('docente', 'Docente del CEPRE', 40, TRUE),
('postulante', 'Postulante / estudiante', 20, TRUE),
('coordinador_administrativo', 'Coordinación administrativa', 70, FALSE)
ON CONFLICT ("NOMBRE_ROL") DO NOTHING;

-- Permisos de ejemplo
INSERT INTO "PERMISOS" ("RECURSO", "ACCION", "DESCRIPCION") VALUES
('usuarios', 'ver', 'Ver usuarios'),
('usuarios', 'crear', 'Crear usuarios'),
('usuarios', 'editar', 'Editar usuarios'),
('usuarios', 'eliminar', 'Eliminar usuarios'),
('postulantes', 'ver', 'Ver postulantes'),
('postulantes', 'crear', 'Crear postulantes'),
('postulantes', 'editar', 'Editar postulantes'),
('docentes', 'ver', 'Ver docentes'),
('docentes', 'crear', 'Crear docentes'),
('docentes', 'editar', 'Editar docentes'),
('asistencias', 'tomar', 'Tomar asistencia'),
('asistencias', 'ver', 'Ver asistencia'),
('grupos', 'ver', 'Ver grupos'),
('grupos', 'editar', 'Editar grupos'),
('periodos', 'ver', 'Ver periodos'),
('periodos', 'crear', 'Crear periodos')
ON CONFLICT ("RECURSO", "ACCION") DO NOTHING;

-- Admin tiene todos los permisos
UPDATE "ROLES"
SET "ID_PERMISOS" = (
  SELECT array_agg("ID_PERMISO" ORDER BY "ID_PERMISO")
  FROM "PERMISOS"
  WHERE "ACTIVO" = TRUE
)
WHERE "NOMBRE_ROL" = 'admin';

-- Areas
INSERT INTO "AREAS" ("NOMBRE_AREA", "CODIGO_AREA", "ACTIVO") VALUES
('INGENIERIAS', 'ING', TRUE),
('SOCIALES', 'SOCI', TRUE),
('SALUD', 'SAL', TRUE)
ON CONFLICT ("NOMBRE_AREA") DO NOTHING;

-- Sedes
INSERT INTO "SEDES" ("NOMBRE_SEDE", "CODIGO_SEDE", "ACTIVO") VALUES
('MOQUEGUA', 'MOQ', TRUE),
('ILO', 'ILO', TRUE)
ON CONFLICT ("NOMBRE_SEDE") DO NOTHING;

-- Cursos
INSERT INTO "CURSOS" ("CODIGO_CURSO", "NOMBRE_CURSO", "EJE_TEMATICO", "COLOR", "ACTIVO") VALUES
('MAT-I', 'ARITMETICA-ALGEBRA', 'MATEMATICAS', '#00FFFF', TRUE),
('MAT-II', 'GEOMETRIA-TRIGONOMETRIA', 'MATEMATICAS', '#505050', TRUE),
('RM', 'RAZONAMIENTO MATEMATICO', 'MATEMATICAS', '#92D050', TRUE),
('LENG', 'LENGUAJE', 'COMUNICACION', '#FF66CC', TRUE),
('LIT', 'LITERATURA', 'COMUNICACION', '#8E1390', TRUE),
('RV', 'RAZONAMIENTO VERBAL', 'COMUNICACION', '#FFC000', TRUE),
('HIST', 'HISTORIA', 'CIENCIAS SOCIALES', '#C00000', TRUE),
('GEO', 'GEOGRAFIA', 'CIENCIAS SOCIALES', '#84AEAE', TRUE),
('ECO', 'ECONOMIA', 'CIENCIAS SOCIALES', '#F44336', TRUE),
('BIO', 'BIOLOGIA', 'CIENCIAS NATURALES', '#4472C4', TRUE),
('FIS', 'FISICA', 'CIENCIAS NATURALES', '#FFFF00', TRUE),
('QUIM', 'QUIMICA', 'CIENCIAS NATURALES', '#E6E6E6', TRUE);

-- Carreras
INSERT INTO "CARRERAS" ("NOMBRE_CARRERA", "CODIGO_CARRERA", "ID_AREA", "ID_SEDES", "ACTIVO") VALUES
('INGENIERIA CIVIL', 'ING-CIV', (SELECT "ID_AREA" FROM "AREAS" WHERE "NOMBRE_AREA" = 'INGENIERIAS'), (SELECT array_agg("ID_SEDE") FROM "SEDES" WHERE "NOMBRE_SEDE" = 'MOQUEGUA'), TRUE),
('INGENIERIA AGROINDUSTRIAL', 'ING-AGRO', (SELECT "ID_AREA" FROM "AREAS" WHERE "NOMBRE_AREA" = 'INGENIERIAS'), (SELECT array_agg("ID_SEDE") FROM "SEDES" WHERE "NOMBRE_SEDE" = 'MOQUEGUA'), TRUE),
('INGENIERIA DE MINAS', 'ING-MIN', (SELECT "ID_AREA" FROM "AREAS" WHERE "NOMBRE_AREA" = 'INGENIERIAS'), (SELECT array_agg("ID_SEDE") FROM "SEDES" WHERE "NOMBRE_SEDE" = 'MOQUEGUA'), TRUE),
('GESTION PUBLICA Y DESARROLLO SOCIAL', 'GPDS', (SELECT "ID_AREA" FROM "AREAS" WHERE "NOMBRE_AREA" = 'SOCIALES'), (SELECT array_agg("ID_SEDE") FROM "SEDES" WHERE "NOMBRE_SEDE" = 'MOQUEGUA'), TRUE),
('INGENIERIA AMBIENTAL', 'ING-AMB', (SELECT "ID_AREA" FROM "AREAS" WHERE "NOMBRE_AREA" = 'INGENIERIAS'), (SELECT array_agg("ID_SEDE") FROM "SEDES" WHERE "NOMBRE_SEDE" = 'ILO'), TRUE),
('INGENIERIA PESQUERA', 'ING-PESQ', (SELECT "ID_AREA" FROM "AREAS" WHERE "NOMBRE_AREA" = 'INGENIERIAS'), (SELECT array_agg("ID_SEDE") FROM "SEDES" WHERE "NOMBRE_SEDE" = 'ILO'), TRUE),
('ADMINISTRACION', 'ADMIN', (SELECT "ID_AREA" FROM "AREAS" WHERE "NOMBRE_AREA" = 'SOCIALES'), (SELECT array_agg("ID_SEDE") FROM "SEDES" WHERE "NOMBRE_SEDE" = 'ILO'), TRUE),
('INGENIERIA DE SISTEMAS E INFORMATICA', 'ING-SIST', (SELECT "ID_AREA" FROM "AREAS" WHERE "NOMBRE_AREA" = 'INGENIERIAS'), (SELECT array_agg("ID_SEDE") FROM "SEDES" WHERE "NOMBRE_SEDE" = 'ILO'), TRUE),
('MEDICINA', 'MED', (SELECT "ID_AREA" FROM "AREAS" WHERE "NOMBRE_AREA" = 'SALUD'), (SELECT array_agg("ID_SEDE") FROM "SEDES" WHERE "NOMBRE_SEDE" = 'MOQUEGUA'), TRUE),
('DERECHO', 'DER', (SELECT "ID_AREA" FROM "AREAS" WHERE "NOMBRE_AREA" = 'SOCIALES'), (SELECT array_agg("ID_SEDE") FROM "SEDES" WHERE "NOMBRE_SEDE" IN ('MOQUEGUA','ILO')), TRUE),
('CONTABILIDAD', 'CONT', (SELECT "ID_AREA" FROM "AREAS" WHERE "NOMBRE_AREA" = 'SOCIALES'), (SELECT array_agg("ID_SEDE") FROM "SEDES" WHERE "NOMBRE_SEDE" IN ('MOQUEGUA','ILO')), TRUE);

-- Usuario admin inicial (DNI: 00000000, clave: admin123)
INSERT INTO "USUARIOS" ("DNI", "APELLIDOS", "NOMBRES", "EMAIL", "PASSWORD_HASH", "ID_ROLES", "ACTIVO", "REQUIERE_CAMBIO_PASSWORD")
VALUES ('00000000', 'ADMIN', 'ADMIN', 'braytonleonardo12@gmail.com', '$2b$10$Z.zZ/FREcJJw2D0PmHOopO2DsEgNvCLaUmEIotvHho/nVqO0OOKZa', (SELECT array_agg("ID_ROL") FROM "ROLES" WHERE "NOMBRE_ROL" = 'admin'), TRUE, FALSE)
ON CONFLICT ("DNI") DO NOTHING;



-- Docentes reales 2026-3 (primer bloque)

INSERT INTO "USUARIOS" ("DNI", "APELLIDOS", "NOMBRES", "SEXO", "EMAIL", "TELEFONO", "PASSWORD_HASH", "ID_ROLES", "ACTIVO", "REQUIERE_CAMBIO_PASSWORD")
VALUES ('29305837', 'AQUIJE CHACON', 'PABLO ALBERTO', 'M', 'acuaries04248@gmail.com', '960832832', '$2b$10$2kjAsbjQKBdC73U6utFqs.ZjtkbbrOj4N8b98xvIpI7SyqBEURUOe', '{}', TRUE, TRUE)
ON CONFLICT ("DNI") DO NOTHING;

INSERT INTO "DOCENTES" ("ID_USUARIO", "RUC", "CONDICION_LABORAL", "ACTIVO")
SELECT u."ID_USUARIO", '10293058372', 'CONTRATADO', TRUE
FROM "USUARIOS" u WHERE u."DNI" = '29305837'
ON CONFLICT ("ID_USUARIO") DO NOTHING;

INSERT INTO "USUARIOS" ("DNI", "APELLIDOS", "NOMBRES", "SEXO", "EMAIL", "TELEFONO", "PASSWORD_HASH", "ID_ROLES", "ACTIVO", "REQUIERE_CAMBIO_PASSWORD")
VALUES ('44709454', 'UMASI CHILO', 'EDGAR ELOY', 'M', 'edumasic@gmail.com', '958899953', '$2b$10$FojTw8aywtwdyN5PRXmR..04uOZfbl3NbcK6/totxqsvImmBqWiGi', '{}', TRUE, TRUE)
ON CONFLICT ("DNI") DO NOTHING;

INSERT INTO "DOCENTES" ("ID_USUARIO", "RUC", "CONDICION_LABORAL", "ACTIVO")
SELECT u."ID_USUARIO", '10447094547', 'EXTERNO', TRUE
FROM "USUARIOS" u WHERE u."DNI" = '44709454'
ON CONFLICT ("ID_USUARIO") DO NOTHING;

INSERT INTO "USUARIOS" ("DNI", "APELLIDOS", "NOMBRES", "SEXO", "EMAIL", "TELEFONO", "PASSWORD_HASH", "ID_ROLES", "ACTIVO", "REQUIERE_CAMBIO_PASSWORD")
VALUES ('04743955', 'CUAYLA SANTOS', 'YANET MIRIAN', 'F', 'yanetcuayla7@gmail.com', '953527345', '$2b$10$YHfPxqv.XQ5701wRiND6.e8FXCEceBswEZVqsFLesXU8ropeB6lgS', '{}', TRUE, TRUE)
ON CONFLICT ("DNI") DO NOTHING;

INSERT INTO "DOCENTES" ("ID_USUARIO", "RUC", "CONDICION_LABORAL", "ACTIVO")
SELECT u."ID_USUARIO", '10047439553', 'CONTRATADO', TRUE
FROM "USUARIOS" u WHERE u."DNI" = '04743955'
ON CONFLICT ("ID_USUARIO") DO NOTHING;

INSERT INTO "USUARIOS" ("DNI", "APELLIDOS", "NOMBRES", "SEXO", "EMAIL", "TELEFONO", "PASSWORD_HASH", "ID_ROLES", "ACTIVO", "REQUIERE_CAMBIO_PASSWORD")
VALUES ('47949308', 'VILLENA TAPIA', 'DENIS DEIVIS', 'M', 'denis.villena.tapia@gmail.com', '924245491', '$2b$10$3g2qXbacsJkeBQun08f3IOz.vYU7pADiT7OgHgyWJsqPNZMRogGIK', '{}', TRUE, TRUE)
ON CONFLICT ("DNI") DO NOTHING;

INSERT INTO "DOCENTES" ("ID_USUARIO", "RUC", "CONDICION_LABORAL", "ACTIVO")
SELECT u."ID_USUARIO", '10479493087', 'EXTERNO', TRUE
FROM "USUARIOS" u WHERE u."DNI" = '47949308'
ON CONFLICT ("ID_USUARIO") DO NOTHING;

INSERT INTO "USUARIOS" ("DNI", "APELLIDOS", "NOMBRES", "SEXO", "EMAIL", "TELEFONO", "PASSWORD_HASH", "ID_ROLES", "ACTIVO", "REQUIERE_CAMBIO_PASSWORD")
VALUES ('04406996', 'ROMERO DIAZ', 'PALMIRA ESPERANZA', 'F', 'palmirarome2@hotmail.com', '964425553', '$2b$10$eVfcXtU.BJhnmD3ZrKZKIOKFlGN2tV2AcWI1ky8OPQDlX8oNEQ1UW', '{}', TRUE, TRUE)
ON CONFLICT ("DNI") DO NOTHING;

INSERT INTO "DOCENTES" ("ID_USUARIO", "RUC", "CONDICION_LABORAL", "ACTIVO")
SELECT u."ID_USUARIO", '10044069968', 'CONTRATADO', TRUE
FROM "USUARIOS" u WHERE u."DNI" = '04406996'
ON CONFLICT ("ID_USUARIO") DO NOTHING;

INSERT INTO "USUARIOS" ("DNI", "APELLIDOS", "NOMBRES", "SEXO", "EMAIL", "TELEFONO", "PASSWORD_HASH", "ID_ROLES", "ACTIVO", "REQUIERE_CAMBIO_PASSWORD")
VALUES ('45026714', 'PACHECO SALAS', 'HUBER RODRIGO', 'M', 'rodripacheco2@gmail.com', '961766124', '$2b$10$ci8ZFeT4I9KMB/IJ1zSNNuYvHniHwAYs6o.D8KRYrfo7.DLrbjDx2', '{}', TRUE, TRUE)
ON CONFLICT ("DNI") DO NOTHING;

INSERT INTO "DOCENTES" ("ID_USUARIO", "RUC", "CONDICION_LABORAL", "ACTIVO")
SELECT u."ID_USUARIO", '10450267142', 'CONTRATADO', TRUE
FROM "USUARIOS" u WHERE u."DNI" = '45026714'
ON CONFLICT ("ID_USUARIO") DO NOTHING;

INSERT INTO "USUARIOS" ("DNI", "APELLIDOS", "NOMBRES", "SEXO", "EMAIL", "TELEFONO", "PASSWORD_HASH", "ID_ROLES", "ACTIVO", "REQUIERE_CAMBIO_PASSWORD")
VALUES ('10644262', 'VILLACORTA DAVILA', 'MANUEL', 'M', 'profesorcomunicacion2025@gmail.com', '953955068', '$2b$10$0k/BgeNaLE/mmP3ifcrgTeA3mIqLMGlp0d2.t1STXFjn1CoWMr6lO', '{}', TRUE, TRUE)
ON CONFLICT ("DNI") DO NOTHING;

INSERT INTO "DOCENTES" ("ID_USUARIO", "RUC", "CONDICION_LABORAL", "ACTIVO")
SELECT u."ID_USUARIO", '10106442628', 'EXTERNO', TRUE
FROM "USUARIOS" u WHERE u."DNI" = '10644262'
ON CONFLICT ("ID_USUARIO") DO NOTHING;

INSERT INTO "USUARIOS" ("DNI", "APELLIDOS", "NOMBRES", "SEXO", "EMAIL", "TELEFONO", "PASSWORD_HASH", "ID_ROLES", "ACTIVO", "REQUIERE_CAMBIO_PASSWORD")
VALUES ('04742953', 'CAHUANA QUISPE', 'VICTOR DAMIAN', 'M', 'vdcahuanaq@gmail.com', '959674775', '$2b$10$bK724rFewC7bzn9i/ihvlOXIRWsVOpQxwSLJA7qxBR.SOqL4LE79O', '{}', TRUE, TRUE)
ON CONFLICT ("DNI") DO NOTHING;

INSERT INTO "DOCENTES" ("ID_USUARIO", "RUC", "CONDICION_LABORAL", "ACTIVO")
SELECT u."ID_USUARIO", '10047429531', 'CONTRATADO', TRUE
FROM "USUARIOS" u WHERE u."DNI" = '04742953'
ON CONFLICT ("ID_USUARIO") DO NOTHING;

INSERT INTO "USUARIOS" ("DNI", "APELLIDOS", "NOMBRES", "SEXO", "EMAIL", "TELEFONO", "PASSWORD_HASH", "ID_ROLES", "ACTIVO", "REQUIERE_CAMBIO_PASSWORD")
VALUES ('72908403', 'CENTENO SALAS', 'PAUL MIDWARD', 'M', 'pol456.uniko55@gmail.com', '975096020', '$2b$10$SQFe.Az2R7uIc.JmmV31fOkaKV3iyWRKuGq5i8moTrtjK1ie//i2i', '{}', TRUE, TRUE)
ON CONFLICT ("DNI") DO NOTHING;

INSERT INTO "DOCENTES" ("ID_USUARIO", "RUC", "CONDICION_LABORAL", "ACTIVO")
SELECT u."ID_USUARIO", '10729084030', 'EXTERNO', TRUE
FROM "USUARIOS" u WHERE u."DNI" = '72908403'
ON CONFLICT ("ID_USUARIO") DO NOTHING;

INSERT INTO "USUARIOS" ("DNI", "APELLIDOS", "NOMBRES", "SEXO", "EMAIL", "TELEFONO", "PASSWORD_HASH", "ID_ROLES", "ACTIVO", "REQUIERE_CAMBIO_PASSWORD")
VALUES ('04745011', 'MAMANI CORI', 'VIGIL WUILBER', 'M', 'wuilbermc2019@gmail.com', '953520329', '$2b$10$C9dKvYrFY5ukz4Duifvg3.b.HKBE76YVCDYtgkYlS.xn5gkRDxKpm', '{}', TRUE, TRUE)
ON CONFLICT ("DNI") DO NOTHING;

INSERT INTO "DOCENTES" ("ID_USUARIO", "RUC", "CONDICION_LABORAL", "ACTIVO")
SELECT u."ID_USUARIO", '10047450115', 'CONTRATADO', TRUE
FROM "USUARIOS" u WHERE u."DNI" = '04745011'
ON CONFLICT ("ID_USUARIO") DO NOTHING;

INSERT INTO "USUARIOS" ("DNI", "APELLIDOS", "NOMBRES", "SEXO", "EMAIL", "TELEFONO", "PASSWORD_HASH", "ID_ROLES", "ACTIVO", "REQUIERE_CAMBIO_PASSWORD")
VALUES ('29663272', 'CANAZA CHOQUE', 'RICHAR MOISES', 'M', 'rcanaza40@gmail.com', '990033336', '$2b$10$V84GrJz3h5ZyGCdpBJ7ni.tAi20wLoL5XTR3gGIKSZq/HBklXcAy6', '{}', TRUE, TRUE)
ON CONFLICT ("DNI") DO NOTHING;

INSERT INTO "DOCENTES" ("ID_USUARIO", "RUC", "CONDICION_LABORAL", "ACTIVO")
SELECT u."ID_USUARIO", '10296632720', 'CONTRATADO', TRUE
FROM "USUARIOS" u WHERE u."DNI" = '29663272'
ON CONFLICT ("ID_USUARIO") DO NOTHING;

INSERT INTO "USUARIOS" ("DNI", "APELLIDOS", "NOMBRES", "SEXO", "EMAIL", "TELEFONO", "PASSWORD_HASH", "ID_ROLES", "ACTIVO", "REQUIERE_CAMBIO_PASSWORD")
VALUES ('30418366', 'CHOQUE LLAVE', 'PERCY RONALD', 'M', 'perchoque0872@gmail.com', '978638440', '$2b$10$E7n.M5nvLpT8QtYiHTLNsOpHjvlu1/mSE6W3B03V7/zfqVm0zlQR.', '{}', TRUE, TRUE)
ON CONFLICT ("DNI") DO NOTHING;

INSERT INTO "DOCENTES" ("ID_USUARIO", "RUC", "CONDICION_LABORAL", "ACTIVO")
SELECT u."ID_USUARIO", '10304183662', 'EXTERNO', TRUE
FROM "USUARIOS" u WHERE u."DNI" = '30418366'
ON CONFLICT ("ID_USUARIO") DO NOTHING;

INSERT INTO "USUARIOS" ("DNI", "APELLIDOS", "NOMBRES", "SEXO", "EMAIL", "TELEFONO", "PASSWORD_HASH", "ID_ROLES", "ACTIVO", "REQUIERE_CAMBIO_PASSWORD")
VALUES ('46213112', 'ARO MAMANI', 'JOSE LUIS', 'M', 'qf.josearo@gmail.com', '993604711', '$2b$10$kBPcUt//4KKEeI8uL0yqw.ZjKBpyrM2ulgLob6wTgciHM2LBt4DqW', '{}', TRUE, TRUE)
ON CONFLICT ("DNI") DO NOTHING;

INSERT INTO "DOCENTES" ("ID_USUARIO", "RUC", "CONDICION_LABORAL", "ACTIVO")
SELECT u."ID_USUARIO", '10462131122', 'EXTERNO', TRUE
FROM "USUARIOS" u WHERE u."DNI" = '46213112'
ON CONFLICT ("ID_USUARIO") DO NOTHING;

-- Usuario coordinador académico (DNI: 48633915, clave: 48633915)
INSERT INTO "USUARIOS" ("DNI", "APELLIDOS", "NOMBRES", "EMAIL", "PASSWORD_HASH", "ID_ROLES", "ACTIVO", "REQUIERE_CAMBIO_PASSWORD")
VALUES ('48633915', 'COACOLLO PILCO', 'JOEL SWELKY', 'leo.jc2720@gmail.com', '$2b$10$5cWVs81f.6B01XMauK3jQ.XkPF7Ky3d.gYHsh1eVACCS3fGSj4YzS', (SELECT array_agg("ID_ROL") FROM "ROLES" WHERE "NOMBRE_ROL" = 'coordinador_academico'), TRUE, TRUE)
ON CONFLICT ("DNI") DO NOTHING;

-- Usuario coordinador administrativo (DNI: 77096874, clave: 77096874)
INSERT INTO "USUARIOS" ("DNI", "APELLIDOS", "NOMBRES", "EMAIL", "PASSWORD_HASH", "ID_ROLES", "ACTIVO", "REQUIERE_CAMBIO_PASSWORD")
VALUES ('77096874', 'CORNEJO MAQUERA', 'NELLY DIANA', 'nellydianacm@gmail.com', '$2b$10$/SErYqg1AzUyWcxPP24znez9PLjNjTCz2r2IrOU59qWs/tAyX/Kl2', (SELECT array_agg("ID_ROL") FROM "ROLES" WHERE "NOMBRE_ROL" = 'coordinador_administrativo'), TRUE, TRUE)
ON CONFLICT ("DNI") DO NOTHING;

-- Usuario auxiliar (DNI: 72766266, clave: 72766266)
INSERT INTO "USUARIOS" ("DNI", "APELLIDOS", "NOMBRES", "EMAIL", "PASSWORD_HASH", "ID_ROLES", "ACTIVO", "REQUIERE_CAMBIO_PASSWORD")
VALUES ('72766266', 'VILLANUEVA ARI', 'CARMEN ROSA', 'cv784668@gmail.com', '$2b$10$YGNsp37uYnaXzCbIq38W1egsD4mnurfh8KVKj5iChB024wSwyPiiK', (SELECT array_agg("ID_ROL") FROM "ROLES" WHERE "NOMBRE_ROL" = 'auxiliar'), TRUE, TRUE)
ON CONFLICT ("DNI") DO NOTHING;



-- Cuenta SMTP inicial (cepre@unam.edu.pe)
INSERT INTO "CUENTAS_SMTP" (
    "NOMBRE_CUENTA", "SMTP_HOST", "SMTP_PORT", "SMTP_USER",
    "SMTP_PASS_ENCRYPTED", "SMTP_PASS_IV", "SMTP_PASS_TAG"
) VALUES (
    'CEPRE Principal',
    'smtp.office365.com',
    587,
    'cepre@unam.edu.pe',
    'J4KoNuQdLzyTw5w0',
    'oTyg06iyEz2d6EI7',
    'n6sbwMoOpx/Du9WDQWDzug=='
);

-- Cuenta SMTP por defecto (correo.cepre@unam.edu.pe)
INSERT INTO "CUENTAS_SMTP" (
    "NOMBRE_CUENTA", "SMTP_HOST", "SMTP_PORT", "SMTP_USER",
    "SMTP_PASS_ENCRYPTED", "SMTP_PASS_IV", "SMTP_PASS_TAG"
) VALUES (
    'CEPRE Predeterminado',
    'smtp.office365.com',
    587,
    'correo.cepre@unam.edu.pe',
    '8PECGbHL0qfTVd9S',
    'Q5wSbrNpfBh4tSUB',
    'ih2NpeTy0CNI4qdgKKa4sg=='
);

-- Inserts iniciales TIPOS_CORREO

INSERT INTO "TIPOS_CORREO" ("ID_CUENTA", "NOMBRE_TIPO", "DESCRIPCION", "ENVIO_AUTOMATICO", "MULTI_USUARIO") VALUES
(2, 'password_reset', 'Recuperacion de contrasena - automatico', TRUE, FALSE),
(2, 'notificacion', 'Notificacion/request - requiere aprobacion', FALSE, TRUE),
(2, 'personalizado_masivo', 'Masivo personalizado por filtro (sede/area) - un correo por usuario', FALSE, TRUE);

-- Usuarios docentes faltantes 2026-1 (solo USUARIOS, sin plazas, sedes ni cursos)

INSERT INTO "USUARIOS" ("DNI", "APELLIDOS", "NOMBRES", "SEXO", "EMAIL", "TELEFONO", "PASSWORD_HASH", "ID_ROLES", "ACTIVO", "REQUIERE_CAMBIO_PASSWORD")
VALUES ('29619844', 'QUILLE VARGAS', 'SELMA CONCEPCIÓN', 'F', 'shelquiva@gmail.com', '950754696', '$2b$10$Wc9GEi9C1rzBwxrLRiRq4u9FSHeFmQmJRMDWoZFKQoXzvLzQWRfgu', '{}', TRUE, TRUE)
ON CONFLICT ("DNI") DO NOTHING;

INSERT INTO "USUARIOS" ("DNI", "APELLIDOS", "NOMBRES", "SEXO", "EMAIL", "TELEFONO", "PASSWORD_HASH", "ID_ROLES", "ACTIVO", "REQUIERE_CAMBIO_PASSWORD")
VALUES ('73599494', 'HUERTA LOZA', 'JHON JERLY', 'M', 'Jhonmatteo1010@gmail.com', '981298587', '$2b$10$kVDxuGj1n/5CzzoQITSFpOPlPA5Moz7xmSgc9qHBELqIOOBEygk3G', '{}', TRUE, TRUE)
ON CONFLICT ("DNI") DO NOTHING;

INSERT INTO "USUARIOS" ("DNI", "APELLIDOS", "NOMBRES", "SEXO", "EMAIL", "TELEFONO", "PASSWORD_HASH", "ID_ROLES", "ACTIVO", "REQUIERE_CAMBIO_PASSWORD")
VALUES ('04626448', 'QUENAYA BEJARANO', 'ELIZABETH MARLENE', 'F', 'elizabethquenaya087@gmail.com', '992959475', '$2b$10$Gx6tSjRSZu.4iMK1WTh7zu/N2XGaEk1vt0CfdNIjbJtQG9OJsZdRi', '{}', TRUE, TRUE)
ON CONFLICT ("DNI") DO NOTHING;

INSERT INTO "USUARIOS" ("DNI", "APELLIDOS", "NOMBRES", "SEXO", "EMAIL", "TELEFONO", "PASSWORD_HASH", "ID_ROLES", "ACTIVO", "REQUIERE_CAMBIO_PASSWORD")
VALUES ('29447951', 'CASTRO GAUNA', 'ALICIA MERCEDES', 'F', 'lic.acastrogauna1@gmail.com', '987826652', '$2b$10$5Z8Sj0LyBWIHsLpeazOkx.OmOb9Qi8LzFlkxLHtSsSEGIstQjrPR.', '{}', TRUE, TRUE)
ON CONFLICT ("DNI") DO NOTHING;

INSERT INTO "USUARIOS" ("DNI", "APELLIDOS", "NOMBRES", "SEXO", "EMAIL", "TELEFONO", "PASSWORD_HASH", "ID_ROLES", "ACTIVO", "REQUIERE_CAMBIO_PASSWORD")
VALUES ('00799213', 'GONZALES PIZARRO', 'CARMEN LETICIA', 'F', 'carmengonzalespi@gmail.com', '955872322', '$2b$10$RZ3W9F62tmcZtCbfTB5fjedTKTfqP794tQs.b2z9u54DU6XCYSveC', '{}', TRUE, TRUE)
ON CONFLICT ("DNI") DO NOTHING;

INSERT INTO "USUARIOS" ("DNI", "APELLIDOS", "NOMBRES", "SEXO", "EMAIL", "TELEFONO", "PASSWORD_HASH", "ID_ROLES", "ACTIVO", "REQUIERE_CAMBIO_PASSWORD")
VALUES ('04647456', 'FLORES CONDORI', 'ISABEL ELISA', 'F', 'isabelfloresc54@gmail.com', '944821390', '$2b$10$SEQUIy2hEVc7dnQpAar4u.c0Ss3YH4a/tkkXddmFPbAFrBGELaAla', '{}', TRUE, TRUE)
ON CONFLICT ("DNI") DO NOTHING;

INSERT INTO "USUARIOS" ("DNI", "APELLIDOS", "NOMBRES", "SEXO", "EMAIL", "TELEFONO", "PASSWORD_HASH", "ID_ROLES", "ACTIVO", "REQUIERE_CAMBIO_PASSWORD")
VALUES ('72787595', 'CATACHURA MAQUERA', 'DEYSI APRIL', 'F', 'acatachuramaquera@gmail.com', '946696531', '$2b$10$tTNyujmEpaCXxTZaeZQnP.kkGWB2/nTftqPcV7N6DmNczlKwkdAye', '{}', TRUE, TRUE)
ON CONFLICT ("DNI") DO NOTHING;

INSERT INTO "USUARIOS" ("DNI", "APELLIDOS", "NOMBRES", "SEXO", "EMAIL", "TELEFONO", "PASSWORD_HASH", "ID_ROLES", "ACTIVO", "REQUIERE_CAMBIO_PASSWORD")
VALUES ('04640676', 'HUERTAS FLORES', 'EDSON BUENAVENTURA', 'M', 'edsonmlaaa@gmail.com', '952960379', '$2b$10$oHzXnXxcnPqfasXImpWhtuLTvEt6XV7dEwpcNWal8h7L9FKar.h9y', '{}', TRUE, TRUE)
ON CONFLICT ("DNI") DO NOTHING;

INSERT INTO "USUARIOS" ("DNI", "APELLIDOS", "NOMBRES", "SEXO", "EMAIL", "TELEFONO", "PASSWORD_HASH", "ID_ROLES", "ACTIVO", "REQUIERE_CAMBIO_PASSWORD")
VALUES ('45047888', 'NAJAR FLORES', 'SUMIRE GIANNINA', 'F', 'giani8815@gmail.com', '931710928', '$2b$10$G1a7bmTwvPsR2hZHvwFqj.SIQ2ewFJaT6P4MxqmQdmUvOuNdhizjK', '{}', TRUE, TRUE)
ON CONFLICT ("DNI") DO NOTHING;

INSERT INTO "USUARIOS" ("DNI", "APELLIDOS", "NOMBRES", "SEXO", "EMAIL", "TELEFONO", "PASSWORD_HASH", "ID_ROLES", "ACTIVO", "REQUIERE_CAMBIO_PASSWORD")
VALUES ('44701882', 'VELAZCO SANTOS', 'JHONATAN JOSE', 'M', 'Velazco_jv@hotmail.com', '953991295', '$2b$10$JNatgoKfVq6JIHQFF.HKuucRKEY4R8AFd/N4NS5v7F0h8iZgQkase', '{}', TRUE, TRUE)
ON CONFLICT ("DNI") DO NOTHING;

-- DOCENTES faltantes 2026-3

INSERT INTO "DOCENTES" ("ID_USUARIO", "RUC", "CONDICION_LABORAL", "ACTIVO")
SELECT u."ID_USUARIO", '10296198442', 'CONTRATADO', TRUE
FROM "USUARIOS" u WHERE u."DNI" = '29619844'
ON CONFLICT ("ID_USUARIO") DO NOTHING;

INSERT INTO "DOCENTES" ("ID_USUARIO", "RUC", "CONDICION_LABORAL", "ACTIVO")
SELECT u."ID_USUARIO", '10735994943', 'CONTRATADO', TRUE
FROM "USUARIOS" u WHERE u."DNI" = '73599494'
ON CONFLICT ("ID_USUARIO") DO NOTHING;

INSERT INTO "DOCENTES" ("ID_USUARIO", "RUC", "CONDICION_LABORAL", "ACTIVO")
SELECT u."ID_USUARIO", '10046264482', 'CONTRATADO', TRUE
FROM "USUARIOS" u WHERE u."DNI" = '04626448'
ON CONFLICT ("ID_USUARIO") DO NOTHING;

INSERT INTO "DOCENTES" ("ID_USUARIO", "RUC", "CONDICION_LABORAL", "ACTIVO")
SELECT u."ID_USUARIO", '10294479517', 'CONTRATADO', TRUE
FROM "USUARIOS" u WHERE u."DNI" = '29447951'
ON CONFLICT ("ID_USUARIO") DO NOTHING;

INSERT INTO "DOCENTES" ("ID_USUARIO", "RUC", "CONDICION_LABORAL", "ACTIVO")
SELECT u."ID_USUARIO", '10007992136', 'CONTRATADO', TRUE
FROM "USUARIOS" u WHERE u."DNI" = '00799213'
ON CONFLICT ("ID_USUARIO") DO NOTHING;

INSERT INTO "DOCENTES" ("ID_USUARIO", "RUC", "CONDICION_LABORAL", "ACTIVO")
SELECT u."ID_USUARIO", '10046474568', 'CONTRATADO', TRUE
FROM "USUARIOS" u WHERE u."DNI" = '04647456'
ON CONFLICT ("ID_USUARIO") DO NOTHING;

INSERT INTO "DOCENTES" ("ID_USUARIO", "RUC", "CONDICION_LABORAL", "ACTIVO")
SELECT u."ID_USUARIO", '10727875951', 'CONTRATADO', TRUE
FROM "USUARIOS" u WHERE u."DNI" = '72787595'
ON CONFLICT ("ID_USUARIO") DO NOTHING;

INSERT INTO "DOCENTES" ("ID_USUARIO", "RUC", "CONDICION_LABORAL", "ACTIVO")
SELECT u."ID_USUARIO", '10046406767', 'CONTRATADO', TRUE
FROM "USUARIOS" u WHERE u."DNI" = '04640676'
ON CONFLICT ("ID_USUARIO") DO NOTHING;

INSERT INTO "DOCENTES" ("ID_USUARIO", "RUC", "CONDICION_LABORAL", "ACTIVO")
SELECT u."ID_USUARIO", '10450478887', 'CONTRATADO', TRUE
FROM "USUARIOS" u WHERE u."DNI" = '45047888'
ON CONFLICT ("ID_USUARIO") DO NOTHING;

INSERT INTO "DOCENTES" ("ID_USUARIO", "RUC", "CONDICION_LABORAL", "ACTIVO")
SELECT u."ID_USUARIO", '10447018824', 'CONTRATADO', TRUE
FROM "USUARIOS" u WHERE u."DNI" = '44701882'
ON CONFLICT ("ID_USUARIO") DO NOTHING;


-- ============================================
-- INSERTS: Aulas - Sede MOQUEGUA
-- ============================================

INSERT INTO "AULAS" ("ID_SEDE", "NOMBRE_AULA", "CODIGO_AULA", "UBICACION", "TIPO", "CAPACIDAD", "ACTIVO")
SELECT s."ID_SEDE", n.nombre, n.codigo, n.ubicacion, 'presencial', 40, TRUE
FROM "SEDES" s
CROSS JOIN (
  VALUES
    ('MEDICINA 301', 'MED-301', '3er piso Pabellón Medicina'),
    ('MEDICINA 302', 'MED-302', '3er piso Pabellón Medicina'),
    ('MEDICINA 303', 'MED-303', '3er piso Pabellón Medicina'),
    ('MEDICINA 304', 'MED-304', '3er piso Pabellón Medicina'),
    ('MEDICINA 201', 'MED-201', '2do piso Pabellón Medicina'),
    ('MEDICINA 202', 'MED-202', '2do piso Pabellón Medicina'),
    ('MINAS 201', 'MIN-201', '2do piso Pabellón Minas'),
    ('MINAS 202', 'MIN-202', '2do piso Pabellón Minas'),
    ('CONTABILIDAD 101', 'CONT-101', '1er piso Pabellón Contabilidad'),
    ('CONTABILIDAD 102', 'CONT-102', '1er piso Pabellón Contabilidad'),
    ('CIVIL 101', 'CIV-101', '1er piso Pabellón Civil'),
    ('CIVIL 102', 'CIV-102', '1er piso Pabellón Civil'),
    ('CIVIL 103', 'CIV-103', '1er piso Pabellón Civil'),
    ('CIVIL 104', 'CIV-104', '1er piso Pabellón Civil')
) AS n(nombre, codigo, ubicacion)
WHERE s."NOMBRE_SEDE" = 'MOQUEGUA'
ON CONFLICT ("ID_SEDE", "NOMBRE_AULA") DO NOTHING;


-- ============================================
-- INSERTS: Aulas virtuales - Sede MOQUEGUA
-- ============================================

-- Aula virtual - Ingenierías
INSERT INTO "AULAS" ("ID_SEDE", "NOMBRE_AULA", "CODIGO_AULA", "UBICACION", "TIPO", "CAPACIDAD", "ACTIVO")
SELECT s."ID_SEDE", 'VIRTUAL INGENIERIAS', 'VIR-ING', 'Aula Virtual', 'virtual', 40, TRUE
FROM "SEDES" s
WHERE s."NOMBRE_SEDE" = 'MOQUEGUA'
ON CONFLICT ("ID_SEDE", "NOMBRE_AULA") DO NOTHING;

-- Aula virtual - Sociales
INSERT INTO "AULAS" ("ID_SEDE", "NOMBRE_AULA", "CODIGO_AULA", "UBICACION", "TIPO", "CAPACIDAD", "ACTIVO")
SELECT s."ID_SEDE", 'VIRTUAL SOCIALES', 'VIR-SOC', 'Aula Virtual', 'virtual', 40, TRUE
FROM "SEDES" s
WHERE s."NOMBRE_SEDE" = 'MOQUEGUA'
ON CONFLICT ("ID_SEDE", "NOMBRE_AULA") DO NOTHING;

-- Aula virtual - Salud
INSERT INTO "AULAS" ("ID_SEDE", "NOMBRE_AULA", "CODIGO_AULA", "UBICACION", "TIPO", "CAPACIDAD", "ACTIVO")
SELECT s."ID_SEDE", 'VIRTUAL SALUD', 'VIR-SAL', 'Aula Virtual', 'virtual', 40, TRUE
FROM "SEDES" s
WHERE s."NOMBRE_SEDE" = 'MOQUEGUA'
ON CONFLICT ("ID_SEDE", "NOMBRE_AULA") DO NOTHING;

