-- ============================================
-- VISTAS: Anuncios, Formularios y Simulacros
-- ============================================

DROP VIEW IF EXISTS "VW_ANUNCIOS";

CREATE OR REPLACE VIEW "VW_ANUNCIOS" AS
SELECT
    a."ID_ANUNCIO",
    a."TITULO",
    a."CONTENIDO",
    a."FECHA_PUBLICACION",
    a."FECHA_INICIO",
    a."FECHA_FIN",
    a."ACTIVO",
    a."ES_GLOBAL",
    a."ID_USUARIO_CREACION",
    u."APELLIDOS" || ' ' || u."NOMBRES" AS "NOMBRE_USUARIO_CREACION",
    u."EMAIL" AS "EMAIL_USUARIO_CREACION",
    COALESCE(array_length(a."ID_ROLES", 1), 0)     AS "CANTIDAD_ROLES",
    COALESCE(array_length(a."ID_PERIODOS", 1), 0)  AS "CANTIDAD_PERIODOS",
    COALESCE(array_length(a."ID_SEDES", 1), 0)     AS "CANTIDAD_SEDES",
    COALESCE(array_length(a."ID_GRUPOS", 1), 0)    AS "CANTIDAD_GRUPOS",
    COALESCE(array_length(a."ID_AREAS", 1), 0)     AS "CANTIDAD_AREAS",
    COALESCE(array_length(a."ID_CARRERAS", 1), 0)  AS "CANTIDAD_CARRERAS"
FROM "ANUNCIOS" a
LEFT JOIN "USUARIOS" u ON u."ID_USUARIO" = a."ID_USUARIO_CREACION";

-- Vista de formularios con filtros y conteos
DROP VIEW IF EXISTS "VW_FORMULARIOS";

CREATE OR REPLACE VIEW "VW_FORMULARIOS" AS
SELECT
    f."ID_FORMULARIO",
    f."TITULO",
    f."DESCRIPCION",
    f."DIRIGIDO_A",
    f."FECHA_INICIO",
    f."FECHA_FIN",
    f."ACTIVO",
    p."CODIGO_PERIODO" || ' - ' || p."NOMBRE_PERIODO" AS "PERIODO_NOMBRE",
    s."NOMBRE_SEDE",
    ar."NOMBRE_AREA",
    c."NOMBRE_CURSO",
    d."ID_DOCENTE",
    u."APELLIDOS" || ' ' || u."NOMBRES" AS "DOCENTE_NOMBRE",
    (
        SELECT COUNT(*) FROM "PREGUNTAS_FORMULARIO" pf
        WHERE pf."ID_FORMULARIO" = f."ID_FORMULARIO" AND pf."ACTIVO" = TRUE
    ) AS "CANTIDAD_PREGUNTAS",
    (
        SELECT COUNT(DISTINCT r."ID_USUARIO") FROM "RESPUESTAS_FORMULARIO" r
        JOIN "PREGUNTAS_FORMULARIO" pf ON pf."ID_PREGUNTA_FORMULARIO" = r."ID_PREGUNTA_FORMULARIO"
        WHERE pf."ID_FORMULARIO" = f."ID_FORMULARIO" AND r."ACTIVO" = TRUE
    ) AS "CANTIDAD_RESPONDEDORES"
FROM "FORMULARIOS" f
LEFT JOIN "PERIODOS" p ON p."ID_PERIODO" = f."ID_PERIODO"
LEFT JOIN "SEDES" s ON s."ID_SEDE" = f."ID_SEDE"
LEFT JOIN "AREAS" ar ON ar."ID_AREA" = f."ID_AREA"
LEFT JOIN "CURSOS" c ON c."ID_CURSO" = f."ID_CURSO"
LEFT JOIN "DOCENTES" d ON d."ID_DOCENTE" = f."ID_DOCENTE"
LEFT JOIN "USUARIOS" u ON u."ID_USUARIO" = d."ID_USUARIO";

-- Vista de preguntas de formulario
DROP VIEW IF EXISTS "VW_PREGUNTAS_FORMULARIO";

CREATE OR REPLACE VIEW "VW_PREGUNTAS_FORMULARIO" AS
SELECT
    pf."ID_PREGUNTA_FORMULARIO",
    pf."ID_FORMULARIO",
    f."TITULO" AS "TITULO_FORMULARIO",
    pf."ORDEN",
    pf."ENUNCIADO",
    pf."TIPO_PREGUNTA",
    pf."OPCIONES",
    pf."MEDIA",
    pf."OBLIGATORIA",
    pf."ACTIVO"
FROM "PREGUNTAS_FORMULARIO" pf
JOIN "FORMULARIOS" f ON f."ID_FORMULARIO" = pf."ID_FORMULARIO";

-- Vista de respuestas de formulario
DROP VIEW IF EXISTS "VW_RESPUESTAS_FORMULARIO";

CREATE OR REPLACE VIEW "VW_RESPUESTAS_FORMULARIO" AS
SELECT
    r."ID_RESPUESTA_FORMULARIO",
    f."ID_FORMULARIO",
    f."TITULO" AS "TITULO_FORMULARIO",
    pf."ID_PREGUNTA_FORMULARIO",
    pf."ENUNCIADO" AS "PREGUNTA",
    r."ID_USUARIO",
    u."APELLIDOS" || ' ' || u."NOMBRES" AS "NOMBRE_USUARIO",
    r."RESPUESTA",
    r."TEXTO",
    r."FECHA_RESPUESTA"
FROM "RESPUESTAS_FORMULARIO" r
JOIN "PREGUNTAS_FORMULARIO" pf ON pf."ID_PREGUNTA_FORMULARIO" = r."ID_PREGUNTA_FORMULARIO"
JOIN "FORMULARIOS" f ON f."ID_FORMULARIO" = pf."ID_FORMULARIO"
JOIN "USUARIOS" u ON u."ID_USUARIO" = r."ID_USUARIO";

-- Vista de simulacros con conteos
DROP VIEW IF EXISTS "VW_SIMULACROS";

CREATE OR REPLACE VIEW "VW_SIMULACROS" AS
SELECT
    s."ID_SIMULACRO",
    s."NOMBRE",
    s."DESCRIPCION",
    s."FECHA_INICIO",
    s."FECHA_FIN",
    s."DURACION_MINUTOS",
    s."ACTIVO",
    p."CODIGO_PERIODO" || ' - ' || p."NOMBRE_PERIODO" AS "PERIODO_NOMBRE",
    se."NOMBRE_SEDE",
    a."NOMBRE_AREA",
    g."NOMBRE_GRUPO",
    (
        SELECT COUNT(*) FROM "PREGUNTAS_SIMULACRO" ps
        WHERE ps."ID_SIMULACRO" = s."ID_SIMULACRO" AND ps."ACTIVO" = TRUE
    ) AS "CANTIDAD_PREGUNTAS",
    (
        SELECT COUNT(DISTINCT r."ID_POSTULANTE") FROM "RESPUESTAS_SIMULACRO" r
        WHERE r."ID_SIMULACRO" = s."ID_SIMULACRO" AND r."ACTIVO" = TRUE
    ) AS "CANTIDAD_POSTULANTES"
FROM "SIMULACROS" s
LEFT JOIN "PERIODOS" p ON p."ID_PERIODO" = s."ID_PERIODO"
LEFT JOIN "SEDES" se ON se."ID_SEDE" = s."ID_SEDE"
LEFT JOIN "AREAS" a ON a."ID_AREA" = s."ID_AREA"
LEFT JOIN "GRUPOS" g ON g."ID_GRUPO" = s."ID_GRUPO";

-- Vista de preguntas de simulacro
DROP VIEW IF EXISTS "VW_PREGUNTAS_SIMULACRO";

CREATE OR REPLACE VIEW "VW_PREGUNTAS_SIMULACRO" AS
SELECT
    ps."ID_PREGUNTA_SIMULACRO",
    ps."ID_SIMULACRO",
    s."NOMBRE" AS "NOMBRE_SIMULACRO",
    ps."ORDEN",
    ps."ENUNCIADO",
    ps."TIPO_PREGUNTA",
    ps."OPCIONES",
    ps."MEDIA",
    ps."RESPUESTA_CORRECTA",
    ps."PUNTAJE",
    ps."ACTIVO"
FROM "PREGUNTAS_SIMULACRO" ps
JOIN "SIMULACROS" s ON s."ID_SIMULACRO" = ps."ID_SIMULACRO";

-- Vista de respuestas de simulacro
DROP VIEW IF EXISTS "VW_RESPUESTAS_SIMULACRO";

CREATE OR REPLACE VIEW "VW_RESPUESTAS_SIMULACRO" AS
SELECT
    r."ID_RESPUESTA_SIMULACRO",
    r."ID_SIMULACRO",
    s."NOMBRE" AS "NOMBRE_SIMULACRO",
    r."ID_POSTULANTE",
    u."APELLIDOS" || ' ' || u."NOMBRES" AS "NOMBRE_POSTULANTE",
    r."FECHA_INICIO",
    r."FECHA_FIN",
    r."PUNTAJE_TOTAL",
    r."RESPUESTAS"
FROM "RESPUESTAS_SIMULACRO" r
JOIN "SIMULACROS" s ON s."ID_SIMULACRO" = r."ID_SIMULACRO"
JOIN "POSTULANTES" po ON po."ID_POSTULANTE" = r."ID_POSTULANTE"
JOIN "USUARIOS" u ON u."ID_USUARIO" = po."ID_USUARIO";
