-- ============================================
-- VISTAS: Plan Académico y sus Cursos
-- ============================================

-- Vista VW_PLAN_ACADEMICO: planes con nombre del área
DROP VIEW IF EXISTS "VW_PLAN_ACADEMICO";
CREATE OR REPLACE VIEW "VW_PLAN_ACADEMICO" AS
SELECT
  pa."ID_PLAN",
  pa."ID_AREA",
  a."NOMBRE_AREA",
  pa."DESCRIPCION",
  pa."ACTIVO"
FROM "PLAN_ACADEMICO" pa
JOIN "AREAS" a ON a."ID_AREA" = pa."ID_AREA";

-- Vista VW_PLAN_ACADEMICO_CURSOS: asignaciones con nombres legibles
DROP VIEW IF EXISTS "VW_PLAN_ACADEMICO_CURSOS";
CREATE OR REPLACE VIEW "VW_PLAN_ACADEMICO_CURSOS" AS
SELECT
  pac."ID_PLAN_ACADEMICO_CURSO",
  pac."ID_PLAN_ACADEMICO",
  pa."DESCRIPCION" AS "DESCRIPCION_PLAN",
  pa."ACTIVO" AS "ACTIVO_PLAN",
  c."ID_CURSO",
  c."NOMBRE_CURSO",
  c."CODIGO_CURSO",
  c."EJE_TEMATICO",
  pac."HORAS_ACADEMICAS_CICLO",
  pac."HORAS_ACADEMICAS_TOTALES",
  pac."ACTIVO"
FROM "PLAN_ACADEMICO_CURSOS" pac
JOIN "PLAN_ACADEMICO" pa ON pa."ID_PLAN" = pac."ID_PLAN_ACADEMICO"
JOIN "CURSOS" c ON c."ID_CURSO" = pac."ID_CURSO";

-- ============================================
-- Vista VW_HORARIOS: plantillas con sede
-- ============================================

DROP VIEW IF EXISTS "VW_HORARIOS";
CREATE OR REPLACE VIEW "VW_HORARIOS" AS
SELECT
  h."ID_HORARIO",
  h."ID_SEDE",
  s."NOMBRE_SEDE",
  h."NOMBRE_HORARIO",
  h."HORA_INICIO_JORNADA",
  h."HORA_FIN_JORNADA",
  h."MATRIZ_DIAS",
  h."ACTIVO"
FROM "HORARIOS" h
JOIN "SEDES" s ON s."ID_SEDE" = h."ID_SEDE";

-- ============================================
-- VISTA: VW_HORARIO_BLOQUES
-- Bloques con horas calculadas, horario y sede
-- ============================================

DROP VIEW IF EXISTS "VW_SEDES_TURNOS_HORARIOS";
DROP VIEW IF EXISTS "VW_HORARIO_BLOQUES";

CREATE OR REPLACE VIEW "VW_HORARIO_BLOQUES" AS
WITH bloques_con_prev AS (
  SELECT
    s."ID_SEDE",
    s."NOMBRE_SEDE",
    h."ID_HORARIO",
    h."NOMBRE_HORARIO",
    h."HORA_INICIO_JORNADA",
    h."HORA_FIN_JORNADA",
    h."ACTIVO" AS "ACTIVO_HORARIO",
    h."MATRIZ_DIAS",
    hb."ID_BLOQUE",
    hb."ORDEN",
    hb."DURACION",
    hb."TIPO_BLOQUE",
    hb."ETIQUETA",
    hb."ACTIVO" AS "ACTIVO_BLOQUE",
    COALESCE(
      SUM(hb."DURACION") OVER (
        PARTITION BY h."ID_HORARIO"
        ORDER BY hb."ORDEN"
        ROWS BETWEEN UNBOUNDED PRECEDING AND 1 PRECEDING
      ),
      0
    ) AS "DURACION_ACUMULADA_ANTERIOR"
  FROM "HORARIOS" h
  JOIN "SEDES" s ON s."ID_SEDE" = h."ID_SEDE"
  JOIN "HORARIO_BLOQUES" hb ON hb."ID_HORARIO" = h."ID_HORARIO"
)
SELECT
  "ID_BLOQUE",
  "ID_HORARIO",
  "ID_SEDE",
  "NOMBRE_SEDE",
  "ORDEN",
  "DURACION",
  "TIPO_BLOQUE",
  "ETIQUETA",
  "ACTIVO_BLOQUE",
  "NOMBRE_HORARIO",
  "HORA_INICIO_JORNADA",
  "HORA_FIN_JORNADA",
  "ACTIVO_HORARIO",
  "MATRIZ_DIAS",
  convertir_matriz_dias_a_texto("MATRIZ_DIAS") AS "MATRIZ_DIAS_TEXTO",
  "DURACION_ACUMULADA_ANTERIOR",
  CASE WHEN "DURACION_ACUMULADA_ANTERIOR" IS NOT NULL AND "HORA_INICIO_JORNADA" IS NOT NULL
       THEN EXTRACT(EPOCH FROM "HORA_INICIO_JORNADA") / 60 + "DURACION_ACUMULADA_ANTERIOR"
       ELSE NULL
  END AS "HORA_INICIO_MINUTOS",
  CASE WHEN "DURACION_ACUMULADA_ANTERIOR" IS NOT NULL AND "HORA_INICIO_JORNADA" IS NOT NULL AND "DURACION" IS NOT NULL
       THEN EXTRACT(EPOCH FROM "HORA_INICIO_JORNADA") / 60 + "DURACION_ACUMULADA_ANTERIOR" + "DURACION"
       ELSE NULL
  END AS "HORA_FIN_MINUTOS",
  CASE WHEN "DURACION_ACUMULADA_ANTERIOR" IS NOT NULL AND "HORA_INICIO_JORNADA" IS NOT NULL
       THEN TO_CHAR(
            "HORA_INICIO_JORNADA" + ("DURACION_ACUMULADA_ANTERIOR" || ' minutes')::INTERVAL,
            'HH24:MI'
          )
       ELSE NULL
  END AS "HORA_INICIO_CALCULADA",
  CASE WHEN "DURACION_ACUMULADA_ANTERIOR" IS NOT NULL AND "HORA_INICIO_JORNADA" IS NOT NULL AND "DURACION" IS NOT NULL
       THEN TO_CHAR(
            "HORA_INICIO_JORNADA" + (("DURACION_ACUMULADA_ANTERIOR" + "DURACION") || ' minutes')::INTERVAL,
            'HH24:MI'
          )
       ELSE NULL
  END AS "HORA_FIN_CALCULADA"
FROM bloques_con_prev
ORDER BY "ID_HORARIO", "ORDEN";
