export const MASIVO_VIEWS = [
  {
    view: 'VW_USUARIOS',
    label: 'Usuarios',
    idField: 'ID_USUARIO',
    emailField: 'EMAIL',
    labelTemplate: '{APELLIDO_PATERNO} {APELLIDO_MATERNO} {NOMBRES} - {EMAIL}',
    descriptionField: 'EMAIL',
    autoMergeFields: true,
    // Fallback: se usa si falla la carga dinámica del schema.
    mergeFields: [
      { field: 'NOMBRE_COMPLETO', label: 'Nombre completo' },
      { field: 'APELLIDO_PATERNO', label: 'Apellido paterno' },
      { field: 'APELLIDO_MATERNO', label: 'Apellido materno' },
      { field: 'NOMBRES', label: 'Nombres' },
      { field: 'DNI', label: 'DNI' },
      { field: 'FECHA_NACIMIENTO', label: 'Fecha de nacimiento' },
      { field: 'EDAD', label: 'Edad' },
      { field: 'SEXO', label: 'Sexo' },
      { field: 'EMAIL', label: 'Email' },
      { field: 'TELEFONO', label: 'Teléfono' },
      { field: 'DIRECCION', label: 'Dirección' },
      { field: 'UBICACION_COMPLETA', label: 'Ubicación' },
      { field: 'DISCAPACIDAD_DESC', label: 'Discapacidad' },
    ],
    filterFields: [
      { field: 'DNI', label: 'DNI', type: 'text' },
      { field: 'NOMBRE_COMPLETO', label: 'Nombre completo', type: 'text' },
      { field: 'FECHA_NACIMIENTO', label: 'Fecha de nacimiento', type: 'date' },
      { field: 'EDAD', label: 'Edad', type: 'number' },
      { field: 'SEXO', label: 'Sexo', type: 'text' },
      { field: 'EMAIL', label: 'Email', type: 'text' },
      { field: 'TELEFONO', label: 'Teléfono', type: 'text' },
      { field: 'DIRECCION', label: 'Dirección', type: 'text' },
      { field: 'UBICACION_COMPLETA', label: 'Ubicación', type: 'text' },
      { field: 'DISCAPACIDAD_DESC', label: 'Discapacidad', type: 'text' },
    ],
  },
  {
    view: 'VW_CORREO_DOCENTES',
    label: 'Docentes con plaza',
    idField: 'ID_DOCENTE',
    emailField: 'EMAIL',
    labelTemplate: '{NOMBRE_COMPLETO} - {EMAIL}',
    descriptionField: 'EMAIL',
    autoMergeFields: true,
    // Fallback: se usa si falla la carga dinámica del schema.
    mergeFields: [
      { field: 'NOMBRE_COMPLETO', label: 'Nombre completo' },
      { field: 'APELLIDO_PATERNO', label: 'Apellido paterno' },
      { field: 'APELLIDO_MATERNO', label: 'Apellido materno' },
      { field: 'NOMBRES', label: 'Nombres' },
      { field: 'DNI', label: 'DNI' },
      { field: 'EMAIL', label: 'Email' },
      { field: 'TELEFONO', label: 'Teléfono' },
      { field: 'TIPO_DOCENTE', label: 'Tipo de docente' },
      { field: 'NOMBRE_PERIODO', label: 'Período' },
      { field: 'TOTAL_PLAZAS', label: 'Total de plazas' },
      { field: 'PLAZAS_RESUMEN', label: 'Plazas (resumen)' },
      { field: 'SEDES', label: 'Sedes' },
      { field: 'CURSOS', label: 'Cursos' },
    ],
    filterFields: [
      { field: 'ID_PERIODO', label: 'ID Período', type: 'number' },
      { field: 'NOMBRE_PERIODO', label: 'Período', type: 'text' },
      { field: 'DNI', label: 'DNI', type: 'text' },
      { field: 'NOMBRE_COMPLETO', label: 'Nombre completo', type: 'text' },
      { field: 'EMAIL', label: 'Email', type: 'text' },
      { field: 'TELEFONO', label: 'Teléfono', type: 'text' },
      { field: 'TIPO_DOCENTE', label: 'Tipo de docente', type: 'text' },
      { field: 'TOTAL_PLAZAS', label: 'Total de plazas', type: 'number' },
    ],
    // Campos extra que deben llegar a rowData (para generar adjuntos / filtros)
    rowDataFields: ['ID_PERIODO', 'NOMBRE_PERIODO'],
    adjuntosPersonalizados: {
      titulo: 'Adjuntar horario del docente',
      descripcion: 'Genera el horario (reporte de docentes) de cada destinatario y lo adjunta solo a su correo.',
      formats: [
        { id: 'pdf', label: 'PDF' },
        { id: 'excel', label: 'Excel' },
      ],
    },
  },
];
