-- =============================================
-- MIGRACIÓN 006: CURSOS
-- Tabla base - Cursos del CEPRE (sin FKs, sin código único)
-- Las relaciones con áreas y coordinadores están en CURSO_AREA
-- =============================================

CREATE TABLE IF NOT EXISTS CURSOS (
  ID_CURSO INTEGER PRIMARY KEY AUTOINCREMENT,
  CODIGO_COMPARTIDO VARCHAR(30) NOT NULL,
  NOMBRE_CURSO VARCHAR(150) NOT NULL,
  EJE_TEMATICO VARCHAR(50) NOT NULL,
  ACTIVO BOOLEAN DEFAULT 1
);

-- Crear índices
CREATE INDEX IF NOT EXISTS IDX_CURSOS_CODIGO_COMPARTIDO ON CURSOS(CODIGO_COMPARTIDO);
CREATE INDEX IF NOT EXISTS IDX_CURSOS_EJE_TEMATICO ON CURSOS(EJE_TEMATICO);

-- Insertar cursos base (sin área específica, sin coordinador, sin horas/créditos)
-- Las horas y créditos se configuran en CURSO_AREA_PERIODO según área y período

INSERT INTO CURSOS (CODIGO_COMPARTIDO, NOMBRE_CURSO, EJE_TEMATICO) VALUES 
  -- MATEMATICAS
  ('MAT-I', 'ARITMETICA-ALGEBRA', 'MATEMATICAS'),
  ('MAT-II', 'GEOMETRIA-TRIGONOMETRIA', 'MATEMATICAS'),
  ('RM', 'RAZONAMIENTO MATEMATICO', 'MATEMATICAS'),
  
  -- COMUNICACION
  ('LENG', 'LENGUAJE', 'COMUNICACION'),
  ('LIT', 'LITERATURA', 'COMUNICACION'),
  ('RV', 'RAZONAMIENTO VERBAL', 'COMUNICACION'),
  
  -- CIENCIAS SOCIALES
  ('HIST', 'HISTORIA', 'CIENCIAS SOCIALES'),
  ('GEO', 'GEOGRAFIA', 'CIENCIAS SOCIALES'),
  ('ECO', 'ECONOMIA', 'CIENCIAS SOCIALES'),
  
  -- CIENCIAS NATURALES
  ('BIO', 'BIOLOGIA', 'CIENCIAS NATURALES'),
  ('FIS', 'FISICA', 'CIENCIAS NATURALES'),
  ('QUIM', 'QUIMICA', 'CIENCIAS NATURALES');
