-- =============================================
-- MIGRACIÓN 008: CURSO_AREA
-- Tabla intermedia N:M - Asignación de cursos a áreas con código único
-- Un curso puede existir en múltiples áreas con códigos diferentes
-- =============================================

CREATE TABLE IF NOT EXISTS CURSO_AREA (
  ID_CURSO_AREA INTEGER PRIMARY KEY AUTOINCREMENT,
  ID_CURSO INTEGER NOT NULL,
  ID_AREA INTEGER NOT NULL,
  CODIGO_UNICO VARCHAR(30) NOT NULL UNIQUE,
  ACTIVO BOOLEAN DEFAULT 1,
  
  -- Foreign Keys
  FOREIGN KEY (ID_CURSO) REFERENCES CURSOS(ID_CURSO) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (ID_AREA) REFERENCES AREAS(ID_AREA) ON DELETE RESTRICT ON UPDATE CASCADE,
  
  -- Un curso solo puede estar una vez por área
  CONSTRAINT UQ_CURSO_AREA UNIQUE (ID_CURSO, ID_AREA)
);

-- Crear índices
CREATE INDEX IF NOT EXISTS IDX_CURSO_AREA_CURSO ON CURSO_AREA(ID_CURSO);
CREATE INDEX IF NOT EXISTS IDX_CURSO_AREA_AREA ON CURSO_AREA(ID_AREA);

-- =============================================
-- MIGRACIÓN 015: CURSO_AREA - Asignación de Cursos a Áreas
-- Inserta las relaciones entre cursos y áreas según configuración CEPRE
-- =============================================

-- =============================================
-- SOCIALES (ID_AREA = 3)
-- Cursos: ARITMETICA-ALGEBRA, GEOMETRIA-TRIGONOMETRIA, RAZONAMIENTO MATEMATICO,
--          LENGUAJE, LITERATURA, RAZONAMIENTO VERBAL, HISTORIA, GEOGRAFIA, ECONOMIA, BIOLOGIA
-- =============================================
INSERT INTO CURSO_AREA (ID_AREA, ID_CURSO, CODIGO_UNICO, ACTIVO) VALUES
  ((SELECT ID_AREA FROM AREAS WHERE NOMBRE_AREA = 'SOCIALES'), (SELECT ID_CURSO FROM CURSOS WHERE CODIGO_COMPARTIDO = 'MAT-I'), 'SOC-MAT-I', 1),
  ((SELECT ID_AREA FROM AREAS WHERE NOMBRE_AREA = 'SOCIALES'), (SELECT ID_CURSO FROM CURSOS WHERE CODIGO_COMPARTIDO = 'MAT-II'), 'SOC-MAT-II', 1),
  ((SELECT ID_AREA FROM AREAS WHERE NOMBRE_AREA = 'SOCIALES'), (SELECT ID_CURSO FROM CURSOS WHERE CODIGO_COMPARTIDO = 'RM'), 'SOC-RM', 1),
  ((SELECT ID_AREA FROM AREAS WHERE NOMBRE_AREA = 'SOCIALES'), (SELECT ID_CURSO FROM CURSOS WHERE CODIGO_COMPARTIDO = 'LENG'), 'SOC-LENG', 1),
  ((SELECT ID_AREA FROM AREAS WHERE NOMBRE_AREA = 'SOCIALES'), (SELECT ID_CURSO FROM CURSOS WHERE CODIGO_COMPARTIDO = 'LIT'), 'SOC-LIT', 1),
  ((SELECT ID_AREA FROM AREAS WHERE NOMBRE_AREA = 'SOCIALES'), (SELECT ID_CURSO FROM CURSOS WHERE CODIGO_COMPARTIDO = 'RV'), 'SOC-RV', 1),
  ((SELECT ID_AREA FROM AREAS WHERE NOMBRE_AREA = 'SOCIALES'), (SELECT ID_CURSO FROM CURSOS WHERE CODIGO_COMPARTIDO = 'HIST'), 'SOC-HIST', 1),
  ((SELECT ID_AREA FROM AREAS WHERE NOMBRE_AREA = 'SOCIALES'), (SELECT ID_CURSO FROM CURSOS WHERE CODIGO_COMPARTIDO = 'GEO'), 'SOC-GEO', 1),
  ((SELECT ID_AREA FROM AREAS WHERE NOMBRE_AREA = 'SOCIALES'), (SELECT ID_CURSO FROM CURSOS WHERE CODIGO_COMPARTIDO = 'ECO'), 'SOC-ECO', 1),
  ((SELECT ID_AREA FROM AREAS WHERE NOMBRE_AREA = 'SOCIALES'), (SELECT ID_CURSO FROM CURSOS WHERE CODIGO_COMPARTIDO = 'BIO'), 'SOC-BIO', 1);

-- =============================================
-- INGENIERIAS (ID_AREA = 1)
-- Cursos: ARITMETICA-ALGEBRA, GEOMETRIA-TRIGONOMETRIA, RAZONAMIENTO MATEMATICO,
--          LENGUAJE, RAZONAMIENTO VERBAL, HISTORIA, GEOGRAFIA, FISICA, QUIMICA, BIOLOGIA
-- =============================================
INSERT INTO CURSO_AREA (ID_AREA, ID_CURSO, CODIGO_UNICO, ACTIVO) VALUES
  ((SELECT ID_AREA FROM AREAS WHERE NOMBRE_AREA = 'INGENIERIAS'), (SELECT ID_CURSO FROM CURSOS WHERE CODIGO_COMPARTIDO = 'MAT-I'), 'ING-MAT-I', 1),
  ((SELECT ID_AREA FROM AREAS WHERE NOMBRE_AREA = 'INGENIERIAS'), (SELECT ID_CURSO FROM CURSOS WHERE CODIGO_COMPARTIDO = 'MAT-II'), 'ING-MAT-II', 1),
  ((SELECT ID_AREA FROM AREAS WHERE NOMBRE_AREA = 'INGENIERIAS'), (SELECT ID_CURSO FROM CURSOS WHERE CODIGO_COMPARTIDO = 'RM'), 'ING-RM', 1),
  ((SELECT ID_AREA FROM AREAS WHERE NOMBRE_AREA = 'INGENIERIAS'), (SELECT ID_CURSO FROM CURSOS WHERE CODIGO_COMPARTIDO = 'LENG'), 'ING-LENG', 1),
  ((SELECT ID_AREA FROM AREAS WHERE NOMBRE_AREA = 'INGENIERIAS'), (SELECT ID_CURSO FROM CURSOS WHERE CODIGO_COMPARTIDO = 'RV'), 'ING-RV', 1),
  ((SELECT ID_AREA FROM AREAS WHERE NOMBRE_AREA = 'INGENIERIAS'), (SELECT ID_CURSO FROM CURSOS WHERE CODIGO_COMPARTIDO = 'HIST'), 'ING-HIST', 1),
  ((SELECT ID_AREA FROM AREAS WHERE NOMBRE_AREA = 'INGENIERIAS'), (SELECT ID_CURSO FROM CURSOS WHERE CODIGO_COMPARTIDO = 'GEO'), 'ING-GEO', 1),
  ((SELECT ID_AREA FROM AREAS WHERE NOMBRE_AREA = 'INGENIERIAS'), (SELECT ID_CURSO FROM CURSOS WHERE CODIGO_COMPARTIDO = 'FIS'), 'ING-FIS', 1),
  ((SELECT ID_AREA FROM AREAS WHERE NOMBRE_AREA = 'INGENIERIAS'), (SELECT ID_CURSO FROM CURSOS WHERE CODIGO_COMPARTIDO = 'QUIM'), 'ING-QUIM', 1),
  ((SELECT ID_AREA FROM AREAS WHERE NOMBRE_AREA = 'INGENIERIAS'), (SELECT ID_CURSO FROM CURSOS WHERE CODIGO_COMPARTIDO = 'BIO'), 'ING-BIO', 1);

-- =============================================
-- SALUD (ID_AREA = 2)
-- Cursos: ARITMETICA-ALGEBRA, GEOMETRIA-TRIGONOMETRIA, RAZONAMIENTO MATEMATICO,
--          RAZONAMIENTO VERBAL, HISTORIA, FISICA, QUIMICA, BIOLOGIA
-- =============================================
INSERT INTO CURSO_AREA (ID_AREA, ID_CURSO, CODIGO_UNICO, ACTIVO) VALUES
  ((SELECT ID_AREA FROM AREAS WHERE NOMBRE_AREA = 'SALUD'), (SELECT ID_CURSO FROM CURSOS WHERE CODIGO_COMPARTIDO = 'MAT-I'), 'SAL-MAT-I', 1),
  ((SELECT ID_AREA FROM AREAS WHERE NOMBRE_AREA = 'SALUD'), (SELECT ID_CURSO FROM CURSOS WHERE CODIGO_COMPARTIDO = 'MAT-II'), 'SAL-MAT-II', 1),
  ((SELECT ID_AREA FROM AREAS WHERE NOMBRE_AREA = 'SALUD'), (SELECT ID_CURSO FROM CURSOS WHERE CODIGO_COMPARTIDO = 'RM'), 'SAL-RM', 1),
  ((SELECT ID_AREA FROM AREAS WHERE NOMBRE_AREA = 'SALUD'), (SELECT ID_CURSO FROM CURSOS WHERE CODIGO_COMPARTIDO = 'LENG'), 'SAL-LENG', 1),
  ((SELECT ID_AREA FROM AREAS WHERE NOMBRE_AREA = 'SALUD'), (SELECT ID_CURSO FROM CURSOS WHERE CODIGO_COMPARTIDO = 'RV'), 'SAL-RV', 1),
  ((SELECT ID_AREA FROM AREAS WHERE NOMBRE_AREA = 'SALUD'), (SELECT ID_CURSO FROM CURSOS WHERE CODIGO_COMPARTIDO = 'HIST'), 'SAL-HIST', 1),
  ((SELECT ID_AREA FROM AREAS WHERE NOMBRE_AREA = 'SALUD'), (SELECT ID_CURSO FROM CURSOS WHERE CODIGO_COMPARTIDO = 'FIS'), 'SAL-FIS', 1),
  ((SELECT ID_AREA FROM AREAS WHERE NOMBRE_AREA = 'SALUD'), (SELECT ID_CURSO FROM CURSOS WHERE CODIGO_COMPARTIDO = 'QUIM'), 'SAL-QUIM', 1),
  ((SELECT ID_AREA FROM AREAS WHERE NOMBRE_AREA = 'SALUD'), (SELECT ID_CURSO FROM CURSOS WHERE CODIGO_COMPARTIDO = 'BIO'), 'SAL-BIO', 1);
