-- =============================================
-- MIGRACIÓN 016: DOCENTE_PERIODO
-- Asignación de docentes a períodos con identificador personalizado
-- =============================================

CREATE TABLE IF NOT EXISTS DOCENTE_PERIODO (
  ID_DOCENTE_PERIODO INTEGER PRIMARY KEY AUTOINCREMENT,
  ID_PERIODO INTEGER NOT NULL,
  ID_DOCENTE INTEGER NULL,
  ID_SEDE INTEGER NOT NULL,
  ID_CURSO INTEGER NOT NULL,
  IDENTIFICADOR_DOCENTE TEXT NOT NULL,
  PAGO_POR_HORA DECIMAL,
  ACTIVO BOOLEAN DEFAULT 1,

  -- Foreign Keys
  FOREIGN KEY (ID_PERIODO) REFERENCES PERIODOS(ID_PERIODO) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (ID_DOCENTE) REFERENCES DOCENTES(ID_DOCENTE) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (ID_SEDE) REFERENCES SEDES(ID_SEDE) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (ID_CURSO) REFERENCES CURSOS(ID_CURSO) ON DELETE CASCADE ON UPDATE CASCADE,

  -- Un docente solo puede estar una vez por período, sede, curso con el mismo identificador
  CONSTRAINT UQ_DOCENTE_PERIODO UNIQUE (ID_PERIODO, ID_SEDE, ID_CURSO, IDENTIFICADOR_DOCENTE)
);

-- Índices
CREATE INDEX IF NOT EXISTS IDX_DOCENTE_PERIODO_PERIODO ON DOCENTE_PERIODO(ID_PERIODO);
CREATE INDEX IF NOT EXISTS IDX_DOCENTE_PERIODO_DOCENTE ON DOCENTE_PERIODO(ID_DOCENTE);
CREATE INDEX IF NOT EXISTS IDX_DOCENTE_PERIODO_SEDE ON DOCENTE_PERIODO(ID_SEDE);
CREATE INDEX IF NOT EXISTS IDX_DOCENTE_PERIODO_CURSO ON DOCENTE_PERIODO(ID_CURSO);

-- Insertar plantillas de docentes para período 2026-III
-- ID_DOCENTE = NULL (plantilla sin docente físico asignado)
INSERT INTO DOCENTE_PERIODO (ID_PERIODO, ID_DOCENTE, ID_SEDE, ID_CURSO, IDENTIFICADOR_DOCENTE, ACTIVO) VALUES
  -- MAT-I
  ((SELECT ID_PERIODO FROM PERIODOS WHERE CODIGO_PERIODO = '2026-III'), NULL, 1, 1, 'MAT-I Moquegua', 1),
  ((SELECT ID_PERIODO FROM PERIODOS WHERE CODIGO_PERIODO = '2026-III'), NULL, 2, 1, 'MAT-I Ilo', 1),
  ((SELECT ID_PERIODO FROM PERIODOS WHERE CODIGO_PERIODO = '2026-III'), NULL, 1, 1, 'MAT-I Moquegua 2', 1),
  -- MAT-II
  ((SELECT ID_PERIODO FROM PERIODOS WHERE CODIGO_PERIODO = '2026-III'), NULL, 1, 2, 'MAT-II Moquegua', 1),
  ((SELECT ID_PERIODO FROM PERIODOS WHERE CODIGO_PERIODO = '2026-III'), NULL, 2, 2, 'MAT-II Ilo', 1),
  ((SELECT ID_PERIODO FROM PERIODOS WHERE CODIGO_PERIODO = '2026-III'), NULL, 1, 2, 'MAT-II Moquegua 2', 1),
  -- RM
  ((SELECT ID_PERIODO FROM PERIODOS WHERE CODIGO_PERIODO = '2026-III'), NULL, 1, 3, 'RM Moquegua', 1),
  ((SELECT ID_PERIODO FROM PERIODOS WHERE CODIGO_PERIODO = '2026-III'), NULL, 2, 3, 'RM Ilo', 1),
  ((SELECT ID_PERIODO FROM PERIODOS WHERE CODIGO_PERIODO = '2026-III'), NULL, 1, 3, 'RM Moquegua 2', 1),
  -- LENG
  ((SELECT ID_PERIODO FROM PERIODOS WHERE CODIGO_PERIODO = '2026-III'), NULL, 1, 4, 'LENG Moquegua', 1),
  ((SELECT ID_PERIODO FROM PERIODOS WHERE CODIGO_PERIODO = '2026-III'), NULL, 2, 4, 'LENG Ilo', 1),
  ((SELECT ID_PERIODO FROM PERIODOS WHERE CODIGO_PERIODO = '2026-III'), NULL, 1, 4, 'LENG Moquegua 2', 1),
  -- LIT
  ((SELECT ID_PERIODO FROM PERIODOS WHERE CODIGO_PERIODO = '2026-III'), NULL, 1, 5, 'LIT Moquegua', 1),
  ((SELECT ID_PERIODO FROM PERIODOS WHERE CODIGO_PERIODO = '2026-III'), NULL, 2, 5, 'LIT Ilo', 1),
  ((SELECT ID_PERIODO FROM PERIODOS WHERE CODIGO_PERIODO = '2026-III'), NULL, 1, 5, 'LIT Moquegua 2', 1),
  -- RV
  ((SELECT ID_PERIODO FROM PERIODOS WHERE CODIGO_PERIODO = '2026-III'), NULL, 1, 6, 'RV Moquegua', 1),
  ((SELECT ID_PERIODO FROM PERIODOS WHERE CODIGO_PERIODO = '2026-III'), NULL, 2, 6, 'RV Ilo', 1),
  ((SELECT ID_PERIODO FROM PERIODOS WHERE CODIGO_PERIODO = '2026-III'), NULL, 1, 6, 'RV Moquegua 2', 1),
  -- HIST
  ((SELECT ID_PERIODO FROM PERIODOS WHERE CODIGO_PERIODO = '2026-III'), NULL, 1, 7, 'HIST Moquegua', 1),
  ((SELECT ID_PERIODO FROM PERIODOS WHERE CODIGO_PERIODO = '2026-III'), NULL, 2, 7, 'HIST Ilo', 1),
  ((SELECT ID_PERIODO FROM PERIODOS WHERE CODIGO_PERIODO = '2026-III'), NULL, 1, 7, 'HIST Moquegua 2', 1),
  -- GEO
  ((SELECT ID_PERIODO FROM PERIODOS WHERE CODIGO_PERIODO = '2026-III'), NULL, 1, 8, 'GEO Moquegua', 1),
  ((SELECT ID_PERIODO FROM PERIODOS WHERE CODIGO_PERIODO = '2026-III'), NULL, 2, 8, 'GEO Ilo', 1),
  ((SELECT ID_PERIODO FROM PERIODOS WHERE CODIGO_PERIODO = '2026-III'), NULL, 1, 8, 'GEO Moquegua 2', 1),
  -- ECO
  ((SELECT ID_PERIODO FROM PERIODOS WHERE CODIGO_PERIODO = '2026-III'), NULL, 1, 9, 'ECO Moquegua', 1),
  ((SELECT ID_PERIODO FROM PERIODOS WHERE CODIGO_PERIODO = '2026-III'), NULL, 2, 9, 'ECO Ilo', 1),
  ((SELECT ID_PERIODO FROM PERIODOS WHERE CODIGO_PERIODO = '2026-III'), NULL, 1, 9, 'ECO Moquegua 2', 1),
  -- BIO
  ((SELECT ID_PERIODO FROM PERIODOS WHERE CODIGO_PERIODO = '2026-III'), NULL, 1, 10, 'BIO Moquegua', 1),
  ((SELECT ID_PERIODO FROM PERIODOS WHERE CODIGO_PERIODO = '2026-III'), NULL, 2, 10, 'BIO Ilo', 1),
  ((SELECT ID_PERIODO FROM PERIODOS WHERE CODIGO_PERIODO = '2026-III'), NULL, 1, 10, 'BIO Moquegua 2', 1),
  -- FIS
  ((SELECT ID_PERIODO FROM PERIODOS WHERE CODIGO_PERIODO = '2026-III'), NULL, 1, 11, 'FIS Moquegua', 1),
  ((SELECT ID_PERIODO FROM PERIODOS WHERE CODIGO_PERIODO = '2026-III'), NULL, 2, 11, 'FIS Ilo', 1),
  ((SELECT ID_PERIODO FROM PERIODOS WHERE CODIGO_PERIODO = '2026-III'), NULL, 1, 11, 'FIS Moquegua 2', 1),
  -- QUIM
  ((SELECT ID_PERIODO FROM PERIODOS WHERE CODIGO_PERIODO = '2026-III'), NULL, 1, 12, 'QUIM Moquegua', 1),
  ((SELECT ID_PERIODO FROM PERIODOS WHERE CODIGO_PERIODO = '2026-III'), NULL, 2, 12, 'QUIM Ilo', 1),
  ((SELECT ID_PERIODO FROM PERIODOS WHERE CODIGO_PERIODO = '2026-III'), NULL, 1, 12, 'QUIM Moquegua 2', 1);
