-- =============================================
-- MIGRACIÓN 018: PLAN_ACADEMICO
-- Cabecera de plan académico (período + área)
-- =============================================

CREATE TABLE IF NOT EXISTS PLAN_ACADEMICO (
  ID_PLAN INTEGER PRIMARY KEY AUTOINCREMENT,
  ID_PERIODO INTEGER NOT NULL,
  ID_AREA INTEGER NOT NULL,
  DESCRIPCION TEXT NOT NULL,
  ACTIVO BOOLEAN DEFAULT 1,
  
  -- Foreign Keys
  FOREIGN KEY (ID_PERIODO) REFERENCES PERIODOS(ID_PERIODO) ON DELETE RESTRICT ON UPDATE CASCADE,
  FOREIGN KEY (ID_AREA) REFERENCES AREAS(ID_AREA) ON DELETE RESTRICT ON UPDATE CASCADE,
  
  -- Un período y área solo pueden tener un plan
  CONSTRAINT UQ_PLAN_ACADEMICO_PERIODO_AREA UNIQUE (ID_PERIODO, ID_AREA)
);

-- Índices
CREATE INDEX IF NOT EXISTS IDX_PLAN_ACADEMICO_PERIODO ON PLAN_ACADEMICO(ID_PERIODO);
CREATE INDEX IF NOT EXISTS IDX_PLAN_ACADEMICO_AREA ON PLAN_ACADEMICO(ID_AREA);

-- Insertar planes académicos para período 2026-III
INSERT INTO PLAN_ACADEMICO (ID_PERIODO, ID_AREA, DESCRIPCION, ACTIVO) VALUES
  ((SELECT ID_PERIODO FROM PERIODOS WHERE CODIGO_PERIODO = '2026-III'), 
   (SELECT ID_AREA FROM AREAS WHERE NOMBRE_AREA = 'INGENIERIAS'), 
   'Plan Académico 2026-III - Ingenierías', 
   1),
  ((SELECT ID_PERIODO FROM PERIODOS WHERE CODIGO_PERIODO = '2026-III'), 
   (SELECT ID_AREA FROM AREAS WHERE NOMBRE_AREA = 'SOCIALES'), 
   'Plan Académico 2026-III - Sociales', 
   1);

