-- =============================================
-- MIGRACIÓN 019: PLAN_ACADEMICO_CURSOS
-- Detalle de plan académico (cursos dentro de un plan)
-- =============================================

CREATE TABLE IF NOT EXISTS PLAN_ACADEMICO_CURSOS (
  ID_PLAN_ACADEMICO_CURSO INTEGER PRIMARY KEY AUTOINCREMENT,
  ID_PLAN_ACADEMICO INTEGER NOT NULL,
  ID_CURSO_AREA INTEGER NOT NULL,
  HORAS_ACADEMICAS_TOTALES INTEGER NOT NULL,
  ACTIVO BOOLEAN DEFAULT 1,
  
  -- Foreign Keys
  FOREIGN KEY (ID_PLAN_ACADEMICO) REFERENCES PLAN_ACADEMICO(ID_PLAN) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (ID_CURSO_AREA) REFERENCES CURSO_AREA(ID_CURSO_AREA) ON DELETE RESTRICT ON UPDATE CASCADE,
  
  -- Un plan no puede tener el mismo curso-área duplicado
  CONSTRAINT UQ_PLAN_ACADEMICO_CURSOS_PLAN_CURSO UNIQUE (ID_PLAN_ACADEMICO, ID_CURSO_AREA)
);

-- Índices
CREATE INDEX IF NOT EXISTS IDX_PLAN_ACADEMICO_CURSOS_PLAN ON PLAN_ACADEMICO_CURSOS(ID_PLAN_ACADEMICO);
CREATE INDEX IF NOT EXISTS IDX_PLAN_ACADEMICO_CURSOS_CURSO_AREA ON PLAN_ACADEMICO_CURSOS(ID_CURSO_AREA);

-- Insertar cursos para plan SOCIALES 2026-III
INSERT INTO PLAN_ACADEMICO_CURSOS (ID_PLAN_ACADEMICO, ID_CURSO_AREA, HORAS_ACADEMICAS_TOTALES, ACTIVO) VALUES
  ((SELECT ID_PLAN FROM PLAN_ACADEMICO WHERE DESCRIPCION = 'Plan Académico 2026-III - Sociales'),
   (SELECT ID_CURSO_AREA FROM CURSO_AREA WHERE CODIGO_UNICO = 'SOC-MAT-I'), 21, 1),
  ((SELECT ID_PLAN FROM PLAN_ACADEMICO WHERE DESCRIPCION = 'Plan Académico 2026-III - Sociales'),
   (SELECT ID_CURSO_AREA FROM CURSO_AREA WHERE CODIGO_UNICO = 'SOC-MAT-II'), 21, 1),
  ((SELECT ID_PLAN FROM PLAN_ACADEMICO WHERE DESCRIPCION = 'Plan Académico 2026-III - Sociales'),
   (SELECT ID_CURSO_AREA FROM CURSO_AREA WHERE CODIGO_UNICO = 'SOC-RM'), 42, 1),
  ((SELECT ID_PLAN FROM PLAN_ACADEMICO WHERE DESCRIPCION = 'Plan Académico 2026-III - Sociales'),
   (SELECT ID_CURSO_AREA FROM CURSO_AREA WHERE CODIGO_UNICO = 'SOC-LENG'), 28, 1),
  ((SELECT ID_PLAN FROM PLAN_ACADEMICO WHERE DESCRIPCION = 'Plan Académico 2026-III - Sociales'),
   (SELECT ID_CURSO_AREA FROM CURSO_AREA WHERE CODIGO_UNICO = 'SOC-LIT'), 21, 1),
  ((SELECT ID_PLAN FROM PLAN_ACADEMICO WHERE DESCRIPCION = 'Plan Académico 2026-III - Sociales'),
   (SELECT ID_CURSO_AREA FROM CURSO_AREA WHERE CODIGO_UNICO = 'SOC-RV'), 42, 1),
  ((SELECT ID_PLAN FROM PLAN_ACADEMICO WHERE DESCRIPCION = 'Plan Académico 2026-III - Sociales'),
   (SELECT ID_CURSO_AREA FROM CURSO_AREA WHERE CODIGO_UNICO = 'SOC-HIST'), 14, 1),
  ((SELECT ID_PLAN FROM PLAN_ACADEMICO WHERE DESCRIPCION = 'Plan Académico 2026-III - Sociales'),
   (SELECT ID_CURSO_AREA FROM CURSO_AREA WHERE CODIGO_UNICO = 'SOC-GEO'), 21, 1),
  ((SELECT ID_PLAN FROM PLAN_ACADEMICO WHERE DESCRIPCION = 'Plan Académico 2026-III - Sociales'),
   (SELECT ID_CURSO_AREA FROM CURSO_AREA WHERE CODIGO_UNICO = 'SOC-ECO'), 21, 1),
  ((SELECT ID_PLAN FROM PLAN_ACADEMICO WHERE DESCRIPCION = 'Plan Académico 2026-III - Sociales'),
   (SELECT ID_CURSO_AREA FROM CURSO_AREA WHERE CODIGO_UNICO = 'SOC-BIO'), 14, 1);

-- Insertar cursos para plan INGENIERIAS 2026-III
INSERT INTO PLAN_ACADEMICO_CURSOS (ID_PLAN_ACADEMICO, ID_CURSO_AREA, HORAS_ACADEMICAS_TOTALES, ACTIVO) VALUES
  ((SELECT ID_PLAN FROM PLAN_ACADEMICO WHERE DESCRIPCION = 'Plan Académico 2026-III - Ingenierías'),
   (SELECT ID_CURSO_AREA FROM CURSO_AREA WHERE CODIGO_UNICO = 'ING-MAT-I'), 28, 1),
  ((SELECT ID_PLAN FROM PLAN_ACADEMICO WHERE DESCRIPCION = 'Plan Académico 2026-III - Ingenierías'),
   (SELECT ID_CURSO_AREA FROM CURSO_AREA WHERE CODIGO_UNICO = 'ING-MAT-II'), 21, 1),
  ((SELECT ID_PLAN FROM PLAN_ACADEMICO WHERE DESCRIPCION = 'Plan Académico 2026-III - Ingenierías'),
   (SELECT ID_CURSO_AREA FROM CURSO_AREA WHERE CODIGO_UNICO = 'ING-RM'), 42, 1),
  ((SELECT ID_PLAN FROM PLAN_ACADEMICO WHERE DESCRIPCION = 'Plan Académico 2026-III - Ingenierías'),
   (SELECT ID_CURSO_AREA FROM CURSO_AREA WHERE CODIGO_UNICO = 'ING-LENG'), 21, 1),
  ((SELECT ID_PLAN FROM PLAN_ACADEMICO WHERE DESCRIPCION = 'Plan Académico 2026-III - Ingenierías'),
   (SELECT ID_CURSO_AREA FROM CURSO_AREA WHERE CODIGO_UNICO = 'ING-RV'), 42, 1),
  ((SELECT ID_PLAN FROM PLAN_ACADEMICO WHERE DESCRIPCION = 'Plan Académico 2026-III - Ingenierías'),
   (SELECT ID_CURSO_AREA FROM CURSO_AREA WHERE CODIGO_UNICO = 'ING-HIST'), 14, 1),
  ((SELECT ID_PLAN FROM PLAN_ACADEMICO WHERE DESCRIPCION = 'Plan Académico 2026-III - Ingenierías'),
   (SELECT ID_CURSO_AREA FROM CURSO_AREA WHERE CODIGO_UNICO = 'ING-GEO'), 14, 1),
  ((SELECT ID_PLAN FROM PLAN_ACADEMICO WHERE DESCRIPCION = 'Plan Académico 2026-III - Ingenierías'),
   (SELECT ID_CURSO_AREA FROM CURSO_AREA WHERE CODIGO_UNICO = 'ING-FIS'), 21, 1),
  ((SELECT ID_PLAN FROM PLAN_ACADEMICO WHERE DESCRIPCION = 'Plan Académico 2026-III - Ingenierías'),
   (SELECT ID_CURSO_AREA FROM CURSO_AREA WHERE CODIGO_UNICO = 'ING-QUIM'), 21, 1),
  ((SELECT ID_PLAN FROM PLAN_ACADEMICO WHERE DESCRIPCION = 'Plan Académico 2026-III - Ingenierías'),
   (SELECT ID_CURSO_AREA FROM CURSO_AREA WHERE CODIGO_UNICO = 'ING-BIO'), 21, 1);
