-- =============================================
-- MIGRACIÓN 011: GRUPOS
-- Tabla con FKs - Grupos de estudio
-- =============================================

CREATE TABLE IF NOT EXISTS GRUPOS (
  ID_GRUPO INTEGER PRIMARY KEY AUTOINCREMENT,
  ID_PERIODO INTEGER NOT NULL,
  ID_AREA INTEGER NOT NULL,
  ID_TURNO INTEGER NOT NULL,
  ID_AULA INTEGER NOT NULL,
  ID_PLAN INTEGER,
  
  DENOMINACION_AULA VARCHAR(100) NOT NULL,
  CODIGO_GRUPO VARCHAR(10) NOT NULL,
  NOMBRE_GRUPO VARCHAR(100) NOT NULL,
  CAPACIDAD_MAXIMA INTEGER,
  ACTIVO BOOLEAN DEFAULT 1,

  -- Foreign Keys
  FOREIGN KEY (ID_AREA) REFERENCES AREAS(ID_AREA) ON DELETE RESTRICT ON UPDATE CASCADE,
  FOREIGN KEY (ID_AULA) REFERENCES AULAS(ID_AULA) ON DELETE RESTRICT ON UPDATE CASCADE,
  FOREIGN KEY (ID_PERIODO) REFERENCES PERIODOS(ID_PERIODO) ON DELETE RESTRICT ON UPDATE CASCADE,
  FOREIGN KEY (ID_TURNO) REFERENCES TURNOS(ID_TURNO) ON DELETE RESTRICT ON UPDATE CASCADE,
  FOREIGN KEY (ID_PLAN) REFERENCES PLAN_ACADEMICO(ID_PLAN) ON DELETE SET NULL ON UPDATE CASCADE,

  -- Restricción única sobre la combinación de área, aula, período y turno
  UNIQUE (ID_PERIODO, ID_AREA, ID_TURNO, ID_AULA)
);

-- Crear índices
CREATE INDEX IF NOT EXISTS IDX_GRUPOS_AULA ON GRUPOS(ID_AULA);
CREATE INDEX IF NOT EXISTS IDX_GRUPOS_PERIODO ON GRUPOS(ID_PERIODO);
CREATE INDEX IF NOT EXISTS IDX_GRUPOS_AREA ON GRUPOS(ID_AREA);
CREATE INDEX IF NOT EXISTS IDX_GRUPOS_TURNO ON GRUPOS(ID_TURNO);
CREATE INDEX IF NOT EXISTS IDX_GRUPOS_CODIGO ON GRUPOS(CODIGO_GRUPO);
CREATE INDEX IF NOT EXISTS IDX_GRUPOS_PLAN ON GRUPOS(ID_PLAN);

-- =============================================
-- INSERTS: Grupos de prueba para período 2026-III
-- 5 grupos de Ingenierías + 3 grupos de Sociales
-- =============================================

-- Grupos Ingenierías (5 grupos en aulas de Medicina)
INSERT INTO GRUPOS (ID_PERIODO, ID_AREA, ID_TURNO, ID_AULA, ID_PLAN, DENOMINACION_AULA, CODIGO_GRUPO, NOMBRE_GRUPO, CAPACIDAD_MAXIMA, ACTIVO) VALUES
  (1, 1, 1, 1, 1, 'G1 ING', 'M-ING-1', 'G1 INGENIERIAS', 40, 1),
  (1, 1, 1, 2, 1, 'G2 ING', 'M-ING-2', 'G2 INGENIERIAS', 40, 1),
  (1, 1, 1, 3, 1, 'G3 ING', 'M-ING-3', 'G3 INGENIERIAS', 40, 1),
  (1, 1, 1, 4, 1, 'G4 ING', 'M-ING-4', 'G4 INGENIERIAS', 40, 1),
  (1, 1, 1, 5, 1, 'G5 ING', 'M-ING-5', 'G5 INGENIERIAS', 40, 1);

-- Grupos Sociales (3 grupos en aulas de Gestión)
INSERT INTO GRUPOS (ID_PERIODO, ID_AREA, ID_TURNO, ID_AULA, ID_PLAN, DENOMINACION_AULA, CODIGO_GRUPO, NOMBRE_GRUPO, CAPACIDAD_MAXIMA, ACTIVO) VALUES
  (1, 3, 1, 6, 2, 'G1 SOCI', 'M-SOCI-1', 'G1 SOCIALES', 40, 1),
  (1, 3, 1, 7, 2, 'G2 SOCI', 'M-SOCI-2', 'G2 SOCIALES', 40, 1),
  (1, 3, 1, 8, 2, 'G3 SOCI', 'M-SOCI-3', 'G3 SOCIALES', 40, 1);

-- Grupos Ilo (4 grupos)
INSERT INTO GRUPOS (ID_PERIODO, ID_AREA, ID_TURNO, ID_AULA, ID_PLAN, DENOMINACION_AULA, CODIGO_GRUPO, NOMBRE_GRUPO, CAPACIDAD_MAXIMA, ACTIVO) VALUES
  (1, 1, 2, 9, 1, 'G1 ING', 'I-ING-1', 'G1 INGENIERIAS', 40, 1),
  (1, 1, 2, 10, 1, 'G2 ING', 'I-ING-2', 'G2 INGENIERIAS', 40, 1),
  (1, 1, 2, 11, 1, 'G3 ING', 'I-ING-3', 'G3 INGENIERIAS', 40, 1),
  (1, 3, 2, 12, 2, 'G1 SOC', 'I-SOC-1', 'G1 SOCIALES', 40, 1);