-- =============================================
-- MIGRACIÓN 021: GRUPO_PLAN_CURSO
-- Asignación de docentes a cursos de plan académico por grupo
-- =============================================

CREATE TABLE IF NOT EXISTS GRUPO_PLAN_CURSO (
  ID_GRUPO_PLAN_CURSO INTEGER PRIMARY KEY AUTOINCREMENT,
  ID_GRUPO INTEGER NOT NULL,
  ID_PLAN_ACADEMICO_CURSO INTEGER NOT NULL,
  ID_DOCENTE_PERIODO INTEGER NULL,
  ACTIVO BOOLEAN DEFAULT 1,
  
  -- Foreign Keys
  FOREIGN KEY (ID_GRUPO) REFERENCES GRUPOS(ID_GRUPO) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (ID_PLAN_ACADEMICO_CURSO) REFERENCES PLAN_ACADEMICO_CURSOS(ID_PLAN_ACADEMICO_CURSO) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (ID_DOCENTE_PERIODO) REFERENCES DOCENTE_PERIODO(ID_DOCENTE_PERIODO) ON DELETE SET NULL ON UPDATE CASCADE,
  
  -- Un grupo no puede tener el mismo curso del plan duplicado
  CONSTRAINT UQ_GRUPO_PLAN_CURSO UNIQUE (ID_GRUPO, ID_PLAN_ACADEMICO_CURSO)
);

-- Índices
CREATE INDEX IF NOT EXISTS IDX_GRUPO_PLAN_CURSO_GRUPO ON GRUPO_PLAN_CURSO(ID_GRUPO);
CREATE INDEX IF NOT EXISTS IDX_GRUPO_PLAN_CURSO_PLAN_CURSO ON GRUPO_PLAN_CURSO(ID_PLAN_ACADEMICO_CURSO);
CREATE INDEX IF NOT EXISTS IDX_GRUPO_PLAN_CURSO_DOCENTE_PERIODO ON GRUPO_PLAN_CURSO(ID_DOCENTE_PERIODO);

-- Insertar cursos en GRUPO_PLAN_CURSO para todos los grupos según su plan académico
-- Cada grupo tendrá todos los cursos de su plan (sin docente asignado por ahora)
INSERT INTO GRUPO_PLAN_CURSO (ID_GRUPO, ID_PLAN_ACADEMICO_CURSO, ID_DOCENTE_PERIODO, ACTIVO)
SELECT
  g.ID_GRUPO,
  pac.ID_PLAN_ACADEMICO_CURSO,
  NULL AS ID_DOCENTE_PERIODO,
  1 AS ACTIVO
FROM GRUPOS g
INNER JOIN PLAN_ACADEMICO_CURSOS pac ON g.ID_PLAN = pac.ID_PLAN_ACADEMICO
WHERE g.ACTIVO = 1
AND pac.ACTIVO = 1
ORDER BY g.ID_GRUPO, pac.ID_PLAN_ACADEMICO_CURSO;

-- Asignar docentes_periodo basado en curso y sede del grupo
UPDATE GRUPO_PLAN_CURSO
SET ID_DOCENTE_PERIODO = (
  SELECT dp.ID_DOCENTE_PERIODO
  FROM DOCENTE_PERIODO dp
  WHERE dp.ID_PERIODO = (
    SELECT g.ID_PERIODO FROM GRUPOS g WHERE g.ID_GRUPO = GRUPO_PLAN_CURSO.ID_GRUPO
  )
  AND dp.ID_SEDE = (
    SELECT au.ID_SEDE
    FROM GRUPOS g
    INNER JOIN AULAS au ON g.ID_AULA = au.ID_AULA
    WHERE g.ID_GRUPO = GRUPO_PLAN_CURSO.ID_GRUPO
  )
  AND dp.ID_CURSO = (
    SELECT ca.ID_CURSO
    FROM PLAN_ACADEMICO_CURSOS pac
    INNER JOIN CURSO_AREA ca ON pac.ID_CURSO_AREA = ca.ID_CURSO_AREA
    WHERE pac.ID_PLAN_ACADEMICO_CURSO = GRUPO_PLAN_CURSO.ID_PLAN_ACADEMICO_CURSO
  )
  AND dp.ACTIVO = 1
  LIMIT 1
)
WHERE ACTIVO = 1;
