-- =============================================
-- MIGRACIÓN 022: ASIGNACION_HORARIO
-- Asignación de bloques de horario a grupo-plan-cursos en fechas específicas
-- =============================================

CREATE TABLE IF NOT EXISTS ASIGNACION_HORARIO (
  ID_ASIGNACION_HORARIO INTEGER PRIMARY KEY AUTOINCREMENT,
  ID_GRUPO_PLAN_CURSO INTEGER NOT NULL,
  ID_HORARIO_BLOQUE INTEGER NOT NULL,
  FECHA DATE NOT NULL,
  
  -- Foreign Keys
  FOREIGN KEY (ID_GRUPO_PLAN_CURSO) REFERENCES GRUPO_PLAN_CURSO(ID_GRUPO_PLAN_CURSO) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (ID_HORARIO_BLOQUE) REFERENCES HORARIO_BLOQUES(ID_BLOQUE) ON DELETE CASCADE ON UPDATE CASCADE,
  
  -- No puede haber duplicado del mismo grupo-plan-curso, bloque y fecha
  CONSTRAINT UQ_ASIGNACION_HORARIO UNIQUE (ID_GRUPO_PLAN_CURSO, ID_HORARIO_BLOQUE, FECHA)
);

-- Índices
CREATE INDEX IF NOT EXISTS IDX_ASIGNACION_HORARIO_GRUPO_PLAN_CURSO ON ASIGNACION_HORARIO(ID_GRUPO_PLAN_CURSO);
CREATE INDEX IF NOT EXISTS IDX_ASIGNACION_HORARIO_HORARIO_BLOQUE ON ASIGNACION_HORARIO(ID_HORARIO_BLOQUE);
CREATE INDEX IF NOT EXISTS IDX_ASIGNACION_HORARIO_FECHA ON ASIGNACION_HORARIO(FECHA);
