-- =============================================
-- VISTA: VW_GRUPO_PLAN_CURSO
-- Muestra grupos con sus cursos de plan académico relacionados
-- =============================================

CREATE VIEW IF NOT EXISTS VW_GRUPO_PLAN_CURSO AS
SELECT 
  -- Datos de GRUPO_PLAN_CURSO
  gpc.ID_GRUPO_PLAN_CURSO,
  gpc.ACTIVO AS ACTIVO_GRUPO_PLAN_CURSO,
  
  -- Datos del GRUPO
  g.ID_GRUPO,
  g.CODIGO_GRUPO,
  g.NOMBRE_GRUPO,
  g.DENOMINACION_AULA,
  g.CAPACIDAD_MAXIMA,
  g.ACTIVO AS ACTIVO_GRUPO,
  
  -- Datos del Área (del grupo)
  ga.ID_AREA AS ID_AREA_GRUPO,
  ga.NOMBRE_AREA AS NOMBRE_AREA_GRUPO,
  
  -- Datos del Aula
  au.ID_AULA,
  au.NOMBRE_AULA,
  au.UBICACION AS UBICACION_AULA,
  au.TIPO AS TIPO_AULA,
  
  -- Datos de la Sede
  s.ID_SEDE,
  s.NOMBRE_SEDE,
  
  -- Datos del Período (del grupo)
  gp.ID_PERIODO AS ID_PERIODO_GRUPO,
  gp.CODIGO_PERIODO AS CODIGO_PERIODO_GRUPO,
  
  -- Datos del Turno
  t.ID_TURNO,
  t.NOMBRE_TURNO,
  t.DESCRIPCION AS DESCRIPCION_TURNO,
  
  -- Datos de PLAN_ACADEMICO_CURSOS
  pac.ID_PLAN_ACADEMICO_CURSO,
  pac.HORAS_ACADEMICAS_TOTALES,
  pac.ACTIVO AS ACTIVO_PLAN_ACADEMICO_CURSO,
  
  -- Datos de CURSO_AREA
  ca.ID_CURSO_AREA,
  ca.CODIGO_UNICO,
  
  -- Datos del CURSO
  c.ID_CURSO,
  c.CODIGO_COMPARTIDO,
  c.NOMBRE_CURSO,
  c.EJE_TEMATICO,
  
  -- Datos del Área (del curso)
  caa.ID_AREA AS ID_AREA_CURSO,
  caa.NOMBRE_AREA AS NOMBRE_AREA_CURSO,
  
  -- Datos de PLAN_ACADEMICO
  pa.ID_PLAN,
  pa.DESCRIPCION AS DESCRIPCION_PLAN,
  pa.ACTIVO AS ACTIVO_PLAN,
  
  -- Datos del Período (del plan)
  pp.ID_PERIODO AS ID_PERIODO_PLAN,
  pp.CODIGO_PERIODO AS CODIGO_PERIODO_PLAN,
  pp.FECHA_INICIO AS FECHA_INICIO_PLAN,
  pp.FECHA_FIN AS FECHA_FIN_PLAN,
  pp.ESTADO AS ESTADO_PLAN,
  
  -- Datos del DOCENTE_PERIODO (LEFT JOIN, puede ser NULL)
  dper.ID_DOCENTE_PERIODO,
  dper.IDENTIFICADOR_DOCENTE,
  dper.ID_SEDE AS ID_SEDE_DOCENTE,
  dper.ID_CURSO AS ID_CURSO_DOCENTE,
  dper.PAGO_POR_HORA,
  
  -- Datos del DOCENTE (LEFT JOIN, puede ser NULL)
  d.ID_DOCENTE,
  COALESCE(d.DNI, 'No asignado') AS DNI,
  COALESCE(d.APELLIDOS, 'No asignado') AS APELLIDOS,
  COALESCE(d.NOMBRES, 'No asignado') AS NOMBRES,
  d.EMAIL,
  COALESCE(d.APELLIDOS || ', ' || d.NOMBRES, 'No asignado') AS NOMBRE_COMPLETO_DOCENTE

FROM GRUPO_PLAN_CURSO gpc
INNER JOIN GRUPOS g ON gpc.ID_GRUPO = g.ID_GRUPO
INNER JOIN AREAS ga ON g.ID_AREA = ga.ID_AREA
INNER JOIN AULAS au ON g.ID_AULA = au.ID_AULA
INNER JOIN SEDES s ON au.ID_SEDE = s.ID_SEDE
INNER JOIN PERIODOS gp ON g.ID_PERIODO = gp.ID_PERIODO
INNER JOIN TURNOS t ON g.ID_TURNO = t.ID_TURNO
INNER JOIN PLAN_ACADEMICO_CURSOS pac ON gpc.ID_PLAN_ACADEMICO_CURSO = pac.ID_PLAN_ACADEMICO_CURSO
INNER JOIN CURSO_AREA ca ON pac.ID_CURSO_AREA = ca.ID_CURSO_AREA
INNER JOIN CURSOS c ON ca.ID_CURSO = c.ID_CURSO
INNER JOIN AREAS caa ON ca.ID_AREA = caa.ID_AREA
INNER JOIN PLAN_ACADEMICO pa ON pac.ID_PLAN_ACADEMICO = pa.ID_PLAN
INNER JOIN PERIODOS pp ON pa.ID_PERIODO = pp.ID_PERIODO
LEFT JOIN DOCENTE_PERIODO dper ON gpc.ID_DOCENTE_PERIODO = dper.ID_DOCENTE_PERIODO
LEFT JOIN DOCENTES d ON dper.ID_DOCENTE = d.ID_DOCENTE;
