-- =============================================
-- VISTA: VW_GRUPOS
-- Muestra grupos con datos completos de área, aula, período y turno
-- =============================================

CREATE VIEW IF NOT EXISTS VW_GRUPOS AS
SELECT 
  g.ID_GRUPO,
  g.CODIGO_GRUPO,
  g.NOMBRE_GRUPO,
  g.DENOMINACION_AULA,
  g.CAPACIDAD_MAXIMA,
  g.ACTIVO AS ACTIVO_GRUPO,
  
  -- Datos del Área
  a.ID_AREA,
  a.NOMBRE_AREA,
  a.ACTIVO AS ACTIVO_AREA,
  
  -- Datos del Aula
  au.ID_AULA,
  au.NOMBRE_AULA,
  au.UBICACION AS UBICACION_AULA,
  au.TIPO AS TIPO_AULA,
  au.ACTIVO AS ACTIVO_AULA,
  
  -- Datos de la Sede
  s.ID_SEDE,
  s.NOMBRE_SEDE,
  s.ACTIVO AS ACTIVO_SEDE,
  
  -- Datos del Período
  p.ID_PERIODO,
  p.CODIGO_PERIODO,
  p.FECHA_INICIO AS FECHA_INICIO_PERIODO,
  p.FECHA_FIN AS FECHA_FIN_PERIODO,
  p.ACTIVO AS ACTIVO_PERIODO,
  
  -- Datos del Turno
  t.ID_TURNO,
  t.NOMBRE_TURNO,
  t.DESCRIPCION AS DESCRIPCION_TURNO,
  t.ACTIVO AS ACTIVO_TURNO,
  
  -- Datos del Plan Académico (LEFT JOIN, puede ser NULL)
  pa.ID_PLAN,
  CASE 
    WHEN pa.DESCRIPCION IS NULL THEN 'SIN PLAN ASIGNADO'
    ELSE pa.DESCRIPCION
  END AS DESCRIPCION_PLAN,
  pa.ACTIVO AS ACTIVO_PLAN

FROM GRUPOS g
INNER JOIN AREAS a ON g.ID_AREA = a.ID_AREA
INNER JOIN AULAS au ON g.ID_AULA = au.ID_AULA
INNER JOIN SEDES s ON au.ID_SEDE = s.ID_SEDE
INNER JOIN PERIODOS p ON g.ID_PERIODO = p.ID_PERIODO
INNER JOIN TURNOS t ON g.ID_TURNO = t.ID_TURNO
LEFT JOIN PLAN_ACADEMICO pa ON g.ID_PLAN = pa.ID_PLAN;
