-- ============================================
-- TABLA: ASISTENCIAS_POSTULANTE
-- ============================================

CREATE TABLE IF NOT EXISTS "ASISTENCIAS_POSTULANTE" (
    "ID_ASISTENCIA"   INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    "ID_POSTULANTE"   INTEGER NOT NULL,
    "ID_SESION"       INTEGER NOT NULL,
    "ASISTIO"         BOOLEAN NULL,
    CONSTRAINT "UQ_ASISTENCIA_POSTULANTE_SESION"
        UNIQUE ("ID_POSTULANTE", "ID_SESION"),
    CONSTRAINT "FK_ASISTENCIA_POSTULANTE"
        FOREIGN KEY ("ID_POSTULANTE") REFERENCES "POSTULANTES" ("ID_POSTULANTE")
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "FK_ASISTENCIA_SESION"
        FOREIGN KEY ("ID_SESION") REFERENCES "SESIONES_AGRUPADAS" ("ID_SESION")
        ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE INDEX IF NOT EXISTS "IDX_ASISTENCIA_POSTULANTE" ON "ASISTENCIAS_POSTULANTE" ("ID_POSTULANTE");
CREATE INDEX IF NOT EXISTS "IDX_ASISTENCIA_SESION"     ON "ASISTENCIAS_POSTULANTE" ("ID_SESION");
CREATE INDEX IF NOT EXISTS "IDX_ASISTENCIA_ASISTIO"    ON "ASISTENCIAS_POSTULANTE" ("ASISTIO") WHERE "ASISTIO" IS NOT NULL;
