-- ============================================
-- TABLAS: CARRERAS, ESTUDIANTES, POSTULANTES
-- ============================================

-- Tabla CARRERAS
CREATE TABLE IF NOT EXISTS "CARRERAS" (
    "ID_CARRERA"     INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    "NOMBRE_CARRERA" VARCHAR(150) NOT NULL,
    "ID_AREA"        INTEGER NOT NULL,
    "ID_SEDE"        INTEGER NOT NULL,
    "ACTIVO"         BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT "FK_CARRERAS_AREA"
        FOREIGN KEY ("ID_AREA") REFERENCES "AREAS" ("ID_AREA")
        ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "FK_CARRERAS_SEDE"
        FOREIGN KEY ("ID_SEDE") REFERENCES "SEDES" ("ID_SEDE")
        ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "UQ_CARRERA_SEDE"
        UNIQUE ("NOMBRE_CARRERA", "ID_SEDE")
);

CREATE INDEX IF NOT EXISTS "IDX_CARRERAS_AREA" ON "CARRERAS" ("ID_AREA");
CREATE INDEX IF NOT EXISTS "IDX_CARRERAS_SEDE" ON "CARRERAS" ("ID_SEDE");

-- Tabla ESTUDIANTES
CREATE TABLE IF NOT EXISTS "ESTUDIANTES" (
    "ID_ESTUDIANTE"  INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    "NOMBRES"        VARCHAR(100) NOT NULL,
    "APELLIDOS"      VARCHAR(100) NOT NULL,
    "ACTIVO"         BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE INDEX IF NOT EXISTS "IDX_ESTUDIANTES_APELLIDOS" ON "ESTUDIANTES" ("APELLIDOS");

-- Tabla POSTULANTES
CREATE TABLE IF NOT EXISTS "POSTULANTES" (
    "ID_POSTULANTE"  INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    "ID_ESTUDIANTE"  INTEGER NOT NULL,
    "ID_PERIODO"     INTEGER NOT NULL,
    "ID_SEDE"        INTEGER NOT NULL,
    "ID_GRUPO"       INTEGER NULL,
    "ID_CARRERA"     INTEGER NULL,
    "ALUMNO_LIBRE"   BOOLEAN NOT NULL DEFAULT FALSE,
    "ACTIVO"         BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT "FK_POSTULANTES_ESTUDIANTE"
        FOREIGN KEY ("ID_ESTUDIANTE") REFERENCES "ESTUDIANTES" ("ID_ESTUDIANTE")
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "FK_POSTULANTES_PERIODO"
        FOREIGN KEY ("ID_PERIODO") REFERENCES "PERIODOS" ("ID_PERIODO")
        ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "FK_POSTULANTES_SEDE"
        FOREIGN KEY ("ID_SEDE") REFERENCES "SEDES" ("ID_SEDE")
        ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "FK_POSTULANTES_GRUPO"
        FOREIGN KEY ("ID_GRUPO") REFERENCES "GRUPOS" ("ID_GRUPO")
        ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "FK_POSTULANTES_CARRERA"
        FOREIGN KEY ("ID_CARRERA") REFERENCES "CARRERAS" ("ID_CARRERA")
        ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "UQ_POSTULANTE_ESTUDIANTE_PERIODO_SEDE"
        UNIQUE ("ID_ESTUDIANTE", "ID_PERIODO", "ID_SEDE")
);

CREATE INDEX IF NOT EXISTS "IDX_POSTULANTES_ESTUDIANTE" ON "POSTULANTES" ("ID_ESTUDIANTE");
CREATE INDEX IF NOT EXISTS "IDX_POSTULANTES_PERIODO"    ON "POSTULANTES" ("ID_PERIODO");
CREATE INDEX IF NOT EXISTS "IDX_POSTULANTES_SEDE"       ON "POSTULANTES" ("ID_SEDE");
CREATE INDEX IF NOT EXISTS "IDX_POSTULANTES_GRUPO"      ON "POSTULANTES" ("ID_GRUPO");
CREATE INDEX IF NOT EXISTS "IDX_POSTULANTES_CARRERA"    ON "POSTULANTES" ("ID_CARRERA");
