-- ============================================
-- ELIMINACIÓN DE TABLAS (si existen)
-- ============================================

DROP TABLE IF EXISTS "PROGRAMACION_GRUPO" CASCADE;
DROP TABLE IF EXISTS "GRUPO_PLAN_CURSO" CASCADE;
DROP TABLE IF EXISTS "GRUPOS" CASCADE;

-- ============================================



CREATE TABLE IF NOT EXISTS "GRUPOS" (
    "ID_GRUPO" INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    "ID_PERIODO" INTEGER NOT NULL,
    "ID_AREA" INTEGER NOT NULL,
    "ID_HORARIO" INTEGER NOT NULL,
    "ID_SEDE" INTEGER NOT NULL,
    "ID_AULA" INTEGER NULL,
    "ID_PLAN" INTEGER NOT NULL,
    "DENOMINACION_AULA" VARCHAR(100) NOT NULL,
    "CODIGO_GRUPO" VARCHAR(30) NOT NULL,
    "NOMBRE_GRUPO" VARCHAR(100) NOT NULL,
    "CAPACIDAD_MAXIMA" INTEGER,
    "FECHA_INICIO" DATE NOT NULL,
    "FECHA_TERMINO" DATE NOT NULL,
    "ACTIVO" BOOLEAN NOT NULL DEFAULT TRUE,

    CONSTRAINT "FK_GRUPOS_AREA"
    FOREIGN KEY ("ID_AREA") REFERENCES "AREAS" ("ID_AREA")
    ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "FK_GRUPOS_AULA"
    FOREIGN KEY ("ID_AULA") REFERENCES "AULAS" ("ID_AULA")
    ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "FK_GRUPOS_PERIODO"
    FOREIGN KEY ("ID_PERIODO") REFERENCES "PERIODOS" ("ID_PERIODO")
    ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "FK_GRUPOS_HORARIO"
    FOREIGN KEY ("ID_HORARIO") REFERENCES "HORARIOS" ("ID_HORARIO")
    ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "FK_GRUPOS_SEDE"
    FOREIGN KEY ("ID_SEDE") REFERENCES "SEDES" ("ID_SEDE")
    ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "FK_GRUPOS_PLAN"
    FOREIGN KEY ("ID_PLAN") REFERENCES "PLAN_ACADEMICO" ("ID_PLAN")
    ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "UQ_GRUPOS_PERIODO_AREA_HORARIO_SEDE_AULA"
    UNIQUE ("ID_PERIODO", "ID_AREA", "ID_HORARIO", "ID_SEDE", "ID_AULA"),
    CONSTRAINT "CK_GRUPOS_FECHAS"
    CHECK ("FECHA_TERMINO" > "FECHA_INICIO")
);

CREATE INDEX IF NOT EXISTS "IDX_GRUPOS_AULA"     ON "GRUPOS" ("ID_AULA");

CREATE INDEX IF NOT EXISTS "IDX_GRUPOS_PERIODO"  ON "GRUPOS" ("ID_PERIODO");

CREATE INDEX IF NOT EXISTS "IDX_GRUPOS_AREA"     ON "GRUPOS" ("ID_AREA");

CREATE INDEX IF NOT EXISTS "IDX_GRUPOS_HORARIO"    ON "GRUPOS" ("ID_HORARIO");

CREATE INDEX IF NOT EXISTS "IDX_GRUPOS_SEDE"     ON "GRUPOS" ("ID_SEDE");

CREATE INDEX IF NOT EXISTS "IDX_GRUPOS_CODIGO"   ON "GRUPOS" ("CODIGO_GRUPO");

CREATE INDEX IF NOT EXISTS "IDX_GRUPOS_PLAN"     ON "GRUPOS" ("ID_PLAN");

-- ============================================

-- TABLA: GRUPO_PLAN_CURSO

-- ============================================

CREATE TABLE IF NOT EXISTS "GRUPO_PLAN_CURSO" (
    "ID_GRUPO_PLAN_CURSO" INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    "ID_GRUPO" INTEGER NOT NULL,
    "ID_PLAN_ACADEMICO_CURSO" INTEGER NOT NULL,
    "ID_PLAZA_DOCENTE" INTEGER NULL,
    "ACTIVO" BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT "FK_GPC_GRUPO"
    FOREIGN KEY ("ID_GRUPO") REFERENCES "GRUPOS" ("ID_GRUPO")
    ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "FK_GPC_PLAN_ACADEMICO_CURSO"
    FOREIGN KEY ("ID_PLAN_ACADEMICO_CURSO") REFERENCES "PLAN_ACADEMICO_CURSOS" ("ID_PLAN_ACADEMICO_CURSO")
    ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "FK_GPC_PLAZA_DOCENTE"
    FOREIGN KEY ("ID_PLAZA_DOCENTE") REFERENCES "PLAZA_DOCENTE" ("ID_PLAZA_DOCENTE")
    ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "UQ_GPC_GRUPO_PLAN_CURSO" UNIQUE ("ID_GRUPO", "ID_PLAN_ACADEMICO_CURSO")
);

CREATE INDEX IF NOT EXISTS "IDX_GPC_GRUPO" ON "GRUPO_PLAN_CURSO" ("ID_GRUPO");

CREATE INDEX IF NOT EXISTS "IDX_GPC_PLAN_ACADEMICO_CURSO" ON "GRUPO_PLAN_CURSO" ("ID_PLAN_ACADEMICO_CURSO");

CREATE INDEX IF NOT EXISTS "IDX_GPC_PLAZA_DOCENTE" ON "GRUPO_PLAN_CURSO" ("ID_PLAZA_DOCENTE");


--DROP TABLE IF EXISTS "PROGRAMACION_GRUPO" CASCADE;

CREATE TABLE IF NOT EXISTS "PROGRAMACION_GRUPO" (
    "ID_PROGRAMACION" INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    "ID_GRUPO" INTEGER NOT NULL,
    "DIA_IDX" INTEGER NOT NULL CHECK ("DIA_IDX" > 0),
    "ID_BLOQUE" INTEGER NOT NULL,
    "ID_GRUPO_PLAN_CURSO" INTEGER NULL,
    "ACTIVO" BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT "FK_PROG_GRUPO"
    FOREIGN KEY ("ID_GRUPO") REFERENCES "GRUPOS" ("ID_GRUPO")
    ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "FK_PROG_BLOQUE"
    FOREIGN KEY ("ID_BLOQUE") REFERENCES "HORARIO_BLOQUES" ("ID_BLOQUE")
    ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "FK_PROG_GRUPO_PLAN_CURSO"
    FOREIGN KEY ("ID_GRUPO_PLAN_CURSO") REFERENCES "GRUPO_PLAN_CURSO" ("ID_GRUPO_PLAN_CURSO")
    ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "UQ_PROG_GRUPO_DIA_BLOQUE"
    UNIQUE ("ID_GRUPO", "DIA_IDX", "ID_BLOQUE")
);

CREATE INDEX IF NOT EXISTS "IDX_PROG_GRUPO_DIA_BLOQUE"

ON "PROGRAMACION_GRUPO" ("ID_GRUPO", "DIA_IDX", "ID_BLOQUE");

CREATE INDEX IF NOT EXISTS "IDX_PROG_GRUPO_PLAN_CURSO"

ON "PROGRAMACION_GRUPO" ("ID_GRUPO_PLAN_CURSO");
