-- ============================================
-- ELIMINACIÓN DE TABLAS (si existen)
-- ============================================

DROP TABLE IF EXISTS "POSTULANTES" CASCADE;

-- ============================================
-- TABLA: POSTULANTES
-- ============================================

CREATE TABLE IF NOT EXISTS "POSTULANTES" (
"ID_POSTULANTE" INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
"ID_USUARIO" INTEGER NOT NULL,
"ID_PERIODO" INTEGER NOT NULL,
"ID_SEDE" INTEGER NOT NULL,
"ID_GRUPO" INTEGER NULL,
"ID_CARRERA" INTEGER NULL,
"CODIGO_ESTUDIANTE" VARCHAR(20) NULL,
"ALUMNO_LIBRE" BOOLEAN NOT NULL DEFAULT FALSE,
"APTO" BOOLEAN NOT NULL DEFAULT TRUE,
"ACTIVO" BOOLEAN NOT NULL DEFAULT TRUE,
CONSTRAINT "FK_POSTULANTES_USUARIO"
FOREIGN KEY ("ID_USUARIO") REFERENCES "USUARIOS" ("ID_USUARIO")
ON DELETE CASCADE ON UPDATE CASCADE,
CONSTRAINT "FK_POSTULANTES_PERIODO"
FOREIGN KEY ("ID_PERIODO") REFERENCES "PERIODOS" ("ID_PERIODO")
ON DELETE RESTRICT ON UPDATE CASCADE,
CONSTRAINT "FK_POSTULANTES_SEDE"
FOREIGN KEY ("ID_SEDE") REFERENCES "SEDES" ("ID_SEDE")
ON DELETE RESTRICT ON UPDATE CASCADE,
CONSTRAINT "FK_POSTULANTES_GRUPO"
FOREIGN KEY ("ID_GRUPO") REFERENCES "GRUPOS" ("ID_GRUPO")
ON DELETE SET NULL ON UPDATE CASCADE,
CONSTRAINT "FK_POSTULANTES_CARRERA"
FOREIGN KEY ("ID_CARRERA") REFERENCES "CARRERAS" ("ID_CARRERA")
ON DELETE SET NULL ON UPDATE CASCADE,
CONSTRAINT "UQ_POSTULANTE_USUARIO_PERIODO"
UNIQUE ("ID_USUARIO", "ID_PERIODO")
);

CREATE INDEX IF NOT EXISTS "IDX_POSTULANTES_USUARIO" ON "POSTULANTES" ("ID_USUARIO");

CREATE INDEX IF NOT EXISTS "IDX_POSTULANTES_PERIODO"    ON "POSTULANTES" ("ID_PERIODO");

CREATE INDEX IF NOT EXISTS "IDX_POSTULANTES_SEDE"       ON "POSTULANTES" ("ID_SEDE");

CREATE INDEX IF NOT EXISTS "IDX_POSTULANTES_GRUPO"      ON "POSTULANTES" ("ID_GRUPO");

CREATE INDEX IF NOT EXISTS "IDX_POSTULANTES_CARRERA"    ON "POSTULANTES" ("ID_CARRERA");
