-- ============================================
-- ELIMINACIÓN DE TABLAS (si existen)
-- ============================================

DROP TABLE IF EXISTS "ASISTENCIAS_POSTULANTE" CASCADE;
DROP TABLE IF EXISTS "SESIONES_AGRUPADAS" CASCADE;

-- ============================================

CREATE TABLE "SESIONES_AGRUPADAS" (
"ID_SESION" INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
"FECHA" DATE NOT NULL,
"ID_GRUPO_PLAN_CURSO" INTEGER NOT NULL,
"HORA_INICIO" TIME NOT NULL,
"HORA_FIN" TIME NOT NULL,
"DURACION_TOTAL_MINUTOS" INTEGER NOT NULL,
-- Bloques con tipo y duración, incluyendo breaks intermedios:
-- [{"id":1,"tipo":"clase","duracion":50},{"id":2,"tipo":"break","duracion":20},{"id":3,"tipo":"clase","duracion":50}]
"IDS_BLOQUES" JSONB NOT NULL DEFAULT '[]',
"IDS_PROGRAMACION" INTEGER[] NOT NULL,
"ESTADO" VARCHAR(20) NOT NULL DEFAULT 'programado'
CHECK ("ESTADO" IN ('programado','realizado','cancelado','reprogramado')),
"ACTIVO" BOOLEAN NOT NULL DEFAULT TRUE,
"ID_DOCENTE_ASISTIO" INTEGER NULL,
"NOMBRE_SUPLENTE_EXTERNO" TEXT NULL,
"ASISTIO" BOOLEAN NULL,
"HORA_ENTRADA_REAL" TIME NULL,
"HORA_SALIDA_REAL" TIME NULL,
"MOTIVO_FALTA" VARCHAR(20) NULL
CHECK ("MOTIVO_FALTA" IN ('licencia','permiso','enfermedad','injustificado','otro') OR "MOTIVO_FALTA" IS NULL),
"OBSERVACIONES" TEXT NULL,
"MARCADO_POR" INTEGER NULL,
"FECHA_MARCADO" TIMESTAMP NULL,
CONSTRAINT "UQ_SESION_AGRUPADA"
UNIQUE ("FECHA", "ID_GRUPO_PLAN_CURSO", "HORA_INICIO"),
CONSTRAINT "FK_SESIONES_GPC"
FOREIGN KEY ("ID_GRUPO_PLAN_CURSO")
REFERENCES "GRUPO_PLAN_CURSO" ("ID_GRUPO_PLAN_CURSO")
ON DELETE CASCADE ON UPDATE CASCADE,
CONSTRAINT "FK_SESIONES_DOC_ASISTIO"
FOREIGN KEY ("ID_DOCENTE_ASISTIO")
REFERENCES "DOCENTES" ("ID_DOCENTE")
ON DELETE SET NULL ON UPDATE CASCADE,
CONSTRAINT "CHK_MOTIVO_SOLO_SI_FALTO"
CHECK ("MOTIVO_FALTA" IS NULL OR "ASISTIO" = FALSE),
CONSTRAINT "CHK_SUPLENTE_UNICO"
CHECK (NOT ("ID_DOCENTE_ASISTIO" IS NOT NULL AND "NOMBRE_SUPLENTE_EXTERNO" IS NOT NULL))
);

CREATE INDEX "IDX_SESIONES_GPC_FECHA"    ON "SESIONES_AGRUPADAS" ("ID_GRUPO_PLAN_CURSO", "FECHA");

CREATE INDEX "IDX_SESIONES_FECHA"        ON "SESIONES_AGRUPADAS" ("FECHA");

CREATE INDEX "IDX_SESIONES_DOC_ASISTIO"  ON "SESIONES_AGRUPADAS" ("ID_DOCENTE_ASISTIO");

CREATE INDEX "IDX_SESIONES_ASISTENCIA"   ON "SESIONES_AGRUPADAS" ("ASISTIO") WHERE "ASISTIO" IS NOT NULL;

-- ============================================

-- TABLA: ASISTENCIAS_POSTULANTE

-- ============================================

CREATE TABLE IF NOT EXISTS "ASISTENCIAS_POSTULANTE" (
"ID_ASISTENCIA" INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
"ID_POSTULANTE" INTEGER NOT NULL,
"ID_SESION" INTEGER NOT NULL,
"ESTADO_ASISTENCIA" VARCHAR(20) NULL,
-- Valores permitidos: 'FALTA', 'ASISTIO', 'TARDANZA', 'JUSTIFICADO'
-- NULL = aún no se ha tomado asistencia
CONSTRAINT "UQ_ASISTENCIA_POSTULANTE_SESION"
UNIQUE ("ID_POSTULANTE", "ID_SESION"),
CONSTRAINT "FK_ASISTENCIA_POSTULANTE"
FOREIGN KEY ("ID_POSTULANTE") REFERENCES "POSTULANTES" ("ID_POSTULANTE")
ON DELETE CASCADE ON UPDATE CASCADE,
CONSTRAINT "FK_ASISTENCIA_SESION"
FOREIGN KEY ("ID_SESION") REFERENCES "SESIONES_AGRUPADAS" ("ID_SESION")
ON DELETE CASCADE ON UPDATE CASCADE,
CONSTRAINT "CHK_ESTADO_ASISTENCIA"
CHECK ("ESTADO_ASISTENCIA" IS NULL OR
"ESTADO_ASISTENCIA" IN ('FALTA', 'ASISTIO', 'TARDANZA', 'JUSTIFICADO'))
);

CREATE INDEX IF NOT EXISTS "IDX_ASISTENCIA_POSTULANTE" ON "ASISTENCIAS_POSTULANTE" ("ID_POSTULANTE");

CREATE INDEX IF NOT EXISTS "IDX_ASISTENCIA_SESION"     ON "ASISTENCIAS_POSTULANTE" ("ID_SESION");

CREATE INDEX IF NOT EXISTS "IDX_ASISTENCIA_ESTADO"     ON "ASISTENCIAS_POSTULANTE" ("ESTADO_ASISTENCIA");
