
-- ============================================

-- ELIMINACIÓN DE TABLAS (si existen)

DROP TABLE IF EXISTS "HORARIO_BLOQUES" CASCADE;
DROP TABLE IF EXISTS "HORARIOS" CASCADE;
DROP TABLE IF EXISTS "PLAN_ACADEMICO_CURSOS" CASCADE;
DROP TABLE IF EXISTS "PLAN_ACADEMICO" CASCADE;

-- ============================================

-- TABLA: PLAN_ACADEMICO

-- ============================================

CREATE TABLE "PLAN_ACADEMICO" (
    "ID_PLAN" INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    "ID_AREA" INTEGER NOT NULL,
    "DESCRIPCION" TEXT UNIQUE NOT NULL,
    "ACTIVO" BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT "FK_PLAN_ACADEMICO_AREA"
    FOREIGN KEY ("ID_AREA") REFERENCES "AREAS" ("ID_AREA")
    ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE INDEX IF NOT EXISTS "IDX_PLAN_ACADEMICO_AREA" ON "PLAN_ACADEMICO" ("ID_AREA");

-- ============================================

-- TABLA: PLAN_ACADEMICO_CURSOS

-- ============================================

CREATE TABLE "PLAN_ACADEMICO_CURSOS" (
    "ID_PLAN_ACADEMICO_CURSO" INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    "ID_PLAN_ACADEMICO" INTEGER NOT NULL,
    "ID_CURSO" INTEGER NOT NULL,
    "HORAS_ACADEMICAS_CICLO" INTEGER NOT NULL,
    "HORAS_ACADEMICAS_TOTALES" INTEGER NOT NULL,
    "ACTIVO" BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT "FK_PLAN_ACADEMICO_CURSOS_PLAN"
    FOREIGN KEY ("ID_PLAN_ACADEMICO") REFERENCES "PLAN_ACADEMICO" ("ID_PLAN")
    ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "FK_PLAN_ACADEMICO_CURSOS_CURSO"
    FOREIGN KEY ("ID_CURSO") REFERENCES "CURSOS" ("ID_CURSO")
    ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "UQ_PLAN_ACADEMICO_CURSOS_PLAN_CURSO"
    UNIQUE ("ID_PLAN_ACADEMICO", "ID_CURSO")
);

CREATE INDEX IF NOT EXISTS "IDX_PLAN_ACADEMICO_CURSOS_PLAN" ON "PLAN_ACADEMICO_CURSOS" ("ID_PLAN_ACADEMICO");

CREATE INDEX IF NOT EXISTS "IDX_PLAN_ACADEMICO_CURSOS_CURSO" ON "PLAN_ACADEMICO_CURSOS" ("ID_CURSO");

-- ============================================

-- TABLAS: HORARIOS Y HORARIO_BLOQUES

-- ============================================

-- Tabla HORARIOS (por sede)

CREATE TABLE "HORARIOS" (
    "ID_HORARIO" INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    "ID_SEDE" INTEGER NOT NULL,
    "NOMBRE_HORARIO" VARCHAR(50) NOT NULL,
    "HORA_INICIO_JORNADA" TIME NOT NULL,
    "HORA_FIN_JORNADA" TIME NOT NULL,
    "ACTIVO" BOOLEAN NOT NULL DEFAULT TRUE,
    "MATRIZ_DIAS" INTEGER[][]
);

-- Índices

CREATE INDEX IF NOT EXISTS "IDX_HORARIOS_SEDE"   ON "HORARIOS" ("ID_SEDE");
CREATE INDEX IF NOT EXISTS "IDX_HORARIOS_NOMBRE" ON "HORARIOS" ("NOMBRE_HORARIO");

-- FK y unicidad por sede/nombre

ALTER TABLE "HORARIOS"
ADD CONSTRAINT "FK_HORARIOS_SEDE"
FOREIGN KEY ("ID_SEDE") REFERENCES "SEDES" ("ID_SEDE")
ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "HORARIOS"
ADD CONSTRAINT "UQ_HORARIOS_SEDE_NOMBRE"
UNIQUE ("ID_SEDE", "NOMBRE_HORARIO");

-- Restricción de validación de la matriz

ALTER TABLE "HORARIOS"
ADD CONSTRAINT "CHK_HORARIOS_MATRIZ_DIAS"
CHECK (validar_matriz_dias("MATRIZ_DIAS"));

-- Tabla HORARIO_BLOQUES

CREATE TABLE "HORARIO_BLOQUES" (
    "ID_BLOQUE" INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    "ID_HORARIO" INTEGER NOT NULL,
    "ORDEN" INTEGER NOT NULL CHECK ("ORDEN" > 0),
    "DURACION" INTEGER NOT NULL CHECK ("DURACION" > 0), -- minutos
    "TIPO_BLOQUE" VARCHAR(10) NOT NULL CHECK ("TIPO_BLOQUE" IN ('clase', 'break')),
    "ETIQUETA" VARCHAR(50),
    "ACTIVO" BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT "FK_HORARIO_BLOQUES_HORARIO"
    FOREIGN KEY ("ID_HORARIO") REFERENCES "HORARIOS" ("ID_HORARIO")
    ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT "UQ_HORARIO_BLOQUE_ORDEN" UNIQUE ("ID_HORARIO", "ORDEN")
);

CREATE INDEX IF NOT EXISTS "IDX_HORARIO_BLOQUES_HORARIO" ON "HORARIO_BLOQUES" ("ID_HORARIO");
