-- ============================================
-- ELIMINACIÓN DE TABLAS (si existen)
-- ============================================

DROP TABLE IF EXISTS "ANUNCIOS_ROLES" CASCADE;
DROP TABLE IF EXISTS "ANUNCIOS_PERIODOS" CASCADE;
DROP TABLE IF EXISTS "ANUNCIOS_SEDES" CASCADE;
DROP TABLE IF EXISTS "ANUNCIOS_GRUPOS" CASCADE;
DROP TABLE IF EXISTS "ANUNCIOS_AREAS" CASCADE;
DROP TABLE IF EXISTS "ANUNCIOS_CARRERAS" CASCADE;
DROP TABLE IF EXISTS "ANUNCIOS" CASCADE;

-- ============================================
-- TABLA: ANUNCIOS
-- Todos los filtros como arrays de IDs
-- ============================================

CREATE TABLE "ANUNCIOS" (
    "ID_ANUNCIO" INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    "TITULO" VARCHAR(200) NOT NULL,
    "CONTENIDO" TEXT NOT NULL,
    "FECHA_PUBLICACION" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "FECHA_INICIO" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "FECHA_FIN" TIMESTAMP,
    "ACTIVO" BOOLEAN NOT NULL DEFAULT TRUE,
    "ES_GLOBAL" BOOLEAN NOT NULL DEFAULT FALSE,
    "ID_USUARIO_CREACION" INTEGER,
    "ID_ROLES" INTEGER[] NOT NULL DEFAULT '{}',
    "ID_PERIODOS" INTEGER[] NOT NULL DEFAULT '{}',
    "ID_SEDES" INTEGER[] NOT NULL DEFAULT '{}',
    "ID_GRUPOS" INTEGER[] NOT NULL DEFAULT '{}',
    "ID_AREAS" INTEGER[] NOT NULL DEFAULT '{}',
    "ID_CARRERAS" INTEGER[] NOT NULL DEFAULT '{}',
    CONSTRAINT "FK_ANUNCIOS_USUARIO"
    FOREIGN KEY ("ID_USUARIO_CREACION") REFERENCES "USUARIOS" ("ID_USUARIO")
    ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "CHK_ANUNCIOS_ROLES_UNICOS"
    CHECK (fn_array_int_sin_duplicados("ID_ROLES")),
    CONSTRAINT "CHK_ANUNCIOS_PERIODOS_UNICOS"
    CHECK (fn_array_int_sin_duplicados("ID_PERIODOS")),
    CONSTRAINT "CHK_ANUNCIOS_SEDES_UNICOS"
    CHECK (fn_array_int_sin_duplicados("ID_SEDES")),
    CONSTRAINT "CHK_ANUNCIOS_GRUPOS_UNICOS"
    CHECK (fn_array_int_sin_duplicados("ID_GRUPOS")),
    CONSTRAINT "CHK_ANUNCIOS_AREAS_UNICOS"
    CHECK (fn_array_int_sin_duplicados("ID_AREAS")),
    CONSTRAINT "CHK_ANUNCIOS_CARRERAS_UNICOS"
    CHECK (fn_array_int_sin_duplicados("ID_CARRERAS"))
);

CREATE INDEX IF NOT EXISTS "IDX_ANUNCIOS_ACTIVO"         ON "ANUNCIOS" ("ACTIVO");
CREATE INDEX IF NOT EXISTS "IDX_ANUNCIOS_FECHA_INICIO"   ON "ANUNCIOS" ("FECHA_INICIO");
CREATE INDEX IF NOT EXISTS "IDX_ANUNCIOS_FECHA_FIN"      ON "ANUNCIOS" ("FECHA_FIN");
CREATE INDEX IF NOT EXISTS "IDX_ANUNCIOS_ES_GLOBAL"      ON "ANUNCIOS" ("ES_GLOBAL");
CREATE INDEX IF NOT EXISTS "IDX_ANUNCIOS_USUARIO_CREACION" ON "ANUNCIOS" ("ID_USUARIO_CREACION");

-- Índices GIN para búsqueda por overlap de arrays

CREATE INDEX IF NOT EXISTS "IDX_ANUNCIOS_ROLES"     ON "ANUNCIOS" USING GIN ("ID_ROLES");
CREATE INDEX IF NOT EXISTS "IDX_ANUNCIOS_PERIODOS"  ON "ANUNCIOS" USING GIN ("ID_PERIODOS");
CREATE INDEX IF NOT EXISTS "IDX_ANUNCIOS_SEDES"     ON "ANUNCIOS" USING GIN ("ID_SEDES");
CREATE INDEX IF NOT EXISTS "IDX_ANUNCIOS_GRUPOS"    ON "ANUNCIOS" USING GIN ("ID_GRUPOS");
CREATE INDEX IF NOT EXISTS "IDX_ANUNCIOS_AREAS"     ON "ANUNCIOS" USING GIN ("ID_AREAS");
CREATE INDEX IF NOT EXISTS "IDX_ANUNCIOS_CARRERAS"  ON "ANUNCIOS" USING GIN ("ID_CARRERAS");

-- ============================================
-- TABLAS: FORMULARIOS Y RESPUESTAS
-- ============================================

CREATE TABLE IF NOT EXISTS "FORMULARIOS" (
    "ID_FORMULARIO" INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    "ID_PERIODO" INTEGER NOT NULL,
    "ID_SEDE" INTEGER,
    "ID_AREA" INTEGER,
    "ID_DOCENTE" INTEGER,
    "ID_CURSO" INTEGER,
    "TITULO" VARCHAR(200) NOT NULL,
    "DESCRIPCION" TEXT,
    "DIRIGIDO_A" VARCHAR(20) NOT NULL DEFAULT 'postulante',
    "FECHA_INICIO" TIMESTAMP,
    "FECHA_FIN" TIMESTAMP,
    "ACTIVO" BOOLEAN NOT NULL DEFAULT TRUE,
    "ID_USUARIO_CREACION" INTEGER,
    CONSTRAINT "CHK_FORMULARIOS_DIRIGIDO_A"
        CHECK ("DIRIGIDO_A" IN ('postulante','docente')),
    CONSTRAINT "FK_FORMULARIOS_PERIODO"
        FOREIGN KEY ("ID_PERIODO") REFERENCES "PERIODOS" ("ID_PERIODO")
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "FK_FORMULARIOS_SEDE"
        FOREIGN KEY ("ID_SEDE") REFERENCES "SEDES" ("ID_SEDE")
        ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "FK_FORMULARIOS_AREA"
        FOREIGN KEY ("ID_AREA") REFERENCES "AREAS" ("ID_AREA")
        ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "FK_FORMULARIOS_DOCENTE"
        FOREIGN KEY ("ID_DOCENTE") REFERENCES "DOCENTES" ("ID_DOCENTE")
        ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "FK_FORMULARIOS_CURSO"
        FOREIGN KEY ("ID_CURSO") REFERENCES "CURSOS" ("ID_CURSO")
        ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "FK_FORMULARIOS_USUARIO"
        FOREIGN KEY ("ID_USUARIO_CREACION") REFERENCES "USUARIOS" ("ID_USUARIO")
        ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE INDEX IF NOT EXISTS "IDX_FORMULARIOS_PERIODO"   ON "FORMULARIOS" ("ID_PERIODO");
CREATE INDEX IF NOT EXISTS "IDX_FORMULARIOS_DIRIGIDO"  ON "FORMULARIOS" ("DIRIGIDO_A");

CREATE TABLE IF NOT EXISTS "PREGUNTAS_FORMULARIO" (
    "ID_PREGUNTA_FORMULARIO" INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    "ID_FORMULARIO" INTEGER NOT NULL,
    "ORDEN" INTEGER NOT NULL DEFAULT 0,
    "ENUNCIADO" TEXT NOT NULL,
    "TIPO_PREGUNTA" VARCHAR(30) NOT NULL DEFAULT 'texto',
    "OPCIONES" JSONB DEFAULT '[]',
    "MEDIA" JSONB DEFAULT '[]',
    "OBLIGATORIA" BOOLEAN NOT NULL DEFAULT TRUE,
    "ACTIVO" BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT "CHK_PREGUNTAS_FORM_TIPO"
        CHECK ("TIPO_PREGUNTA" IN ('texto','seleccion_unica','seleccion_multiple','escala','archivo')),
    CONSTRAINT "FK_PREGUNTAS_FORM_FORMULARIO"
        FOREIGN KEY ("ID_FORMULARIO") REFERENCES "FORMULARIOS" ("ID_FORMULARIO")
        ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE INDEX IF NOT EXISTS "IDX_PREGUNTAS_FORM_FORMULARIO" ON "PREGUNTAS_FORMULARIO" ("ID_FORMULARIO");

CREATE TABLE IF NOT EXISTS "RESPUESTAS_FORMULARIO" (
    "ID_RESPUESTA_FORMULARIO" INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    "ID_PREGUNTA_FORMULARIO" INTEGER NOT NULL,
    "ID_USUARIO" INTEGER NOT NULL,
    "RESPUESTA" JSONB,
    "TEXTO" TEXT,
    "FECHA_RESPUESTA" TIMESTAMP NOT NULL DEFAULT NOW(),
    "ACTIVO" BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT "FK_RESPUESTAS_FORM_PREGUNTA"
        FOREIGN KEY ("ID_PREGUNTA_FORMULARIO") REFERENCES "PREGUNTAS_FORMULARIO" ("ID_PREGUNTA_FORMULARIO")
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "FK_RESPUESTAS_FORM_USUARIO"
        FOREIGN KEY ("ID_USUARIO") REFERENCES "USUARIOS" ("ID_USUARIO")
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "UQ_RESPUESTA_FORM_USUARIO_PREGUNTA"
        UNIQUE ("ID_PREGUNTA_FORMULARIO", "ID_USUARIO")
);

CREATE INDEX IF NOT EXISTS "IDX_RESPUESTAS_FORM_PREGUNTA" ON "RESPUESTAS_FORMULARIO" ("ID_PREGUNTA_FORMULARIO");
CREATE INDEX IF NOT EXISTS "IDX_RESPUESTAS_FORM_USUARIO"    ON "RESPUESTAS_FORMULARIO" ("ID_USUARIO");

-- ============================================
-- TABLAS: SIMULACROS Y RESPUESTAS
-- ============================================

CREATE TABLE IF NOT EXISTS "SIMULACROS" (
    "ID_SIMULACRO" INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    "ID_PERIODO" INTEGER NOT NULL,
    "ID_SEDE" INTEGER,
    "ID_AREA" INTEGER,
    "ID_GRUPO" INTEGER,
    "NOMBRE" VARCHAR(200) NOT NULL,
    "DESCRIPCION" TEXT,
    "FECHA_INICIO" TIMESTAMP,
    "FECHA_FIN" TIMESTAMP,
    "DURACION_MINUTOS" INTEGER,
    "ACTIVO" BOOLEAN NOT NULL DEFAULT TRUE,
    "ID_USUARIO_CREACION" INTEGER,
    CONSTRAINT "FK_SIMULACROS_PERIODO"
        FOREIGN KEY ("ID_PERIODO") REFERENCES "PERIODOS" ("ID_PERIODO")
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "FK_SIMULACROS_SEDE"
        FOREIGN KEY ("ID_SEDE") REFERENCES "SEDES" ("ID_SEDE")
        ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "FK_SIMULACROS_AREA"
        FOREIGN KEY ("ID_AREA") REFERENCES "AREAS" ("ID_AREA")
        ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "FK_SIMULACROS_GRUPO"
        FOREIGN KEY ("ID_GRUPO") REFERENCES "GRUPOS" ("ID_GRUPO")
        ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "FK_SIMULACROS_USUARIO"
        FOREIGN KEY ("ID_USUARIO_CREACION") REFERENCES "USUARIOS" ("ID_USUARIO")
        ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE INDEX IF NOT EXISTS "IDX_SIMULACROS_PERIODO" ON "SIMULACROS" ("ID_PERIODO");
CREATE INDEX IF NOT EXISTS "IDX_SIMULACROS_AREA"     ON "SIMULACROS" ("ID_AREA");
CREATE INDEX IF NOT EXISTS "IDX_SIMULACROS_SEDE"     ON "SIMULACROS" ("ID_SEDE");

CREATE TABLE IF NOT EXISTS "PREGUNTAS_SIMULACRO" (
    "ID_PREGUNTA_SIMULACRO" INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    "ID_SIMULACRO" INTEGER NOT NULL,
    "ORDEN" INTEGER NOT NULL DEFAULT 0,
    "ENUNCIADO" TEXT NOT NULL,
    "TIPO_PREGUNTA" VARCHAR(30) NOT NULL DEFAULT 'seleccion_unica',
    "OPCIONES" JSONB DEFAULT '[]',
    "MEDIA" JSONB DEFAULT '[]',
    "RESPUESTA_CORRECTA" JSONB,
    "PUNTAJE" DECIMAL NOT NULL DEFAULT 0,
    "ACTIVO" BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT "CHK_PREGUNTAS_SIM_TIPO"
        CHECK ("TIPO_PREGUNTA" IN ('texto','seleccion_unica','seleccion_multiple','archivo')),
    CONSTRAINT "FK_PREGUNTAS_SIM_SIMULACRO"
        FOREIGN KEY ("ID_SIMULACRO") REFERENCES "SIMULACROS" ("ID_SIMULACRO")
        ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE INDEX IF NOT EXISTS "IDX_PREGUNTAS_SIM_SIMULACRO" ON "PREGUNTAS_SIMULACRO" ("ID_SIMULACRO");

CREATE TABLE IF NOT EXISTS "RESPUESTAS_SIMULACRO" (
    "ID_RESPUESTA_SIMULACRO" INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    "ID_SIMULACRO" INTEGER NOT NULL,
    "ID_POSTULANTE" INTEGER NOT NULL,
    "FECHA_INICIO" TIMESTAMP,
    "FECHA_FIN" TIMESTAMP,
    "PUNTAJE_TOTAL" DECIMAL DEFAULT 0,
    "RESPUESTAS" JSONB DEFAULT '[]',
    "ACTIVO" BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT "FK_RESPUESTAS_SIM_SIMULACRO"
        FOREIGN KEY ("ID_SIMULACRO") REFERENCES "SIMULACROS" ("ID_SIMULACRO")
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "FK_RESPUESTAS_SIM_POSTULANTE"
        FOREIGN KEY ("ID_POSTULANTE") REFERENCES "POSTULANTES" ("ID_POSTULANTE")
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "UQ_RESPUESTA_SIM_POSTULANTE"
        UNIQUE ("ID_SIMULACRO", "ID_POSTULANTE")
);

CREATE INDEX IF NOT EXISTS "IDX_RESPUESTAS_SIM_SIMULACRO" ON "RESPUESTAS_SIMULACRO" ("ID_SIMULACRO");
CREATE INDEX IF NOT EXISTS "IDX_RESPUESTAS_SIM_POSTULANTE" ON "RESPUESTAS_SIMULACRO" ("ID_POSTULANTE");
