-- ============================================
-- ELIMINACIÓN DE TABLAS (si existen)
-- ============================================

DROP TABLE IF EXISTS "POSTULACION_ADJUNTOS" CASCADE;
DROP TABLE IF EXISTS "POSTULACION_PLAZA" CASCADE;
DROP TABLE IF EXISTS "REQUISITOS_DOCENTES" CASCADE;
DROP TABLE IF EXISTS "PLAZA_DOCENTE" CASCADE;
DROP TABLE IF EXISTS "CONVOCATORIA_CURSO" CASCADE;
DROP TABLE IF EXISTS "CONVOCATORIA" CASCADE;
DROP TABLE IF EXISTS "PERIODOS" CASCADE;

-- ============================================

CREATE TABLE IF NOT EXISTS "PERIODOS" (
    "ID_PERIODO" INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    "CODIGO_PERIODO" VARCHAR(20) NOT NULL UNIQUE,
    "NOMBRE_PERIODO" VARCHAR(50) NOT NULL UNIQUE,
    "FECHA_INICIO" DATE,
    "FECHA_FIN" DATE,
    "ACTIVO" BOOLEAN NOT NULL DEFAULT TRUE
);

-- ============================================
-- CONVOCATORIA: una convocatoria por periodo (UQ ID_PERIODO).
-- Define fechas de apertura/cierre y descripción.
-- Si se vuelve a necesitar, se cambian las fechas de la misma convocatoria.
-- ============================================

CREATE TABLE IF NOT EXISTS "CONVOCATORIA" (
    "ID_CONVOCATORIA" INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    "ID_PERIODO" INTEGER NOT NULL,
    "DESCRIPCION" VARCHAR(200),
    "FECHA_APERTURA" TIMESTAMP NOT NULL DEFAULT NOW(),
    "FECHA_CIERRE" TIMESTAMP,
    "ACTIVO" BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT "FK_CONVOCATORIA_PERIODO"
    FOREIGN KEY ("ID_PERIODO") REFERENCES "PERIODOS" ("ID_PERIODO")
    ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "UQ_CONVOCATORIA_PERIODO"
    UNIQUE ("ID_PERIODO")
);

CREATE INDEX IF NOT EXISTS "IDX_CONVOCATORIA_ACTIVO"
    ON "CONVOCATORIA" ("ACTIVO");

-- ============================================
-- CONVOCATORIA_CURSO: detalle de convocatoria por (sede + curso).
-- Define el número máximo de plazas (slots) a cubrir para ese curso/sede.
-- UQ (ID_CONVOCATORIA + ID_SEDE + ID_CURSO) evita duplicar el mismo
-- curso+sede dentro de la misma convocatoria.
-- ============================================

CREATE TABLE IF NOT EXISTS "CONVOCATORIA_CURSO" (
    "ID_CONVOCATORIA_CURSO" INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    "ID_CONVOCATORIA" INTEGER NOT NULL,
    "ID_SEDE" INTEGER NOT NULL,
    "ID_CURSO" INTEGER NOT NULL,
    "NUMERO_PLAZAS" INTEGER NOT NULL DEFAULT 1
        CHECK ("NUMERO_PLAZAS" >= 0),
    "ACTIVO" BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT "FK_CONVOCATORIA_CURSO_CONVOCATORIA"
    FOREIGN KEY ("ID_CONVOCATORIA") REFERENCES "CONVOCATORIA" ("ID_CONVOCATORIA")
    ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "FK_CONVOCATORIA_CURSO_SEDE"
    FOREIGN KEY ("ID_SEDE") REFERENCES "SEDES" ("ID_SEDE")
    ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "FK_CONVOCATORIA_CURSO_CURSO"
    FOREIGN KEY ("ID_CURSO") REFERENCES "CURSOS" ("ID_CURSO")
    ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "UQ_CONVOCATORIA_CURSO_CONJUNTO"
    UNIQUE ("ID_CONVOCATORIA", "ID_SEDE", "ID_CURSO")
);

CREATE INDEX IF NOT EXISTS "IDX_CONVOCATORIA_CURSO_CONVOCATORIA"
    ON "CONVOCATORIA_CURSO" ("ID_CONVOCATORIA");

CREATE INDEX IF NOT EXISTS "IDX_CONVOCATORIA_CURSO_ACTIVO"
    ON "CONVOCATORIA_CURSO" ("ACTIVO");

CREATE TABLE IF NOT EXISTS "PLAZA_DOCENTE" (
    "ID_PLAZA_DOCENTE" INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    "ID_CONVOCATORIA_CURSO" INTEGER NOT NULL,
    "ID_PERIODO" INTEGER NOT NULL,
    "ID_SEDE" INTEGER NOT NULL,
    "ID_CURSO" INTEGER NOT NULL,
    "PAGO_POR_HORA" DECIMAL,
    "FECHA_CREACION" TIMESTAMP NOT NULL DEFAULT NOW(),
    "ACTIVO" BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT "FK_PLAZA_CONVOCATORIA_CURSO"
    FOREIGN KEY ("ID_CONVOCATORIA_CURSO") REFERENCES "CONVOCATORIA_CURSO" ("ID_CONVOCATORIA_CURSO")
    ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "FK_PLAZA_DOCENTE_PERIODO"
    FOREIGN KEY ("ID_PERIODO") REFERENCES "PERIODOS" ("ID_PERIODO")
    ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "FK_PLAZA_DOCENTE_SEDE"
    FOREIGN KEY ("ID_SEDE") REFERENCES "SEDES" ("ID_SEDE")
    ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "FK_PLAZA_DOCENTE_CURSO"
    FOREIGN KEY ("ID_CURSO") REFERENCES "CURSOS" ("ID_CURSO")
    ON DELETE CASCADE ON UPDATE CASCADE
);

-- ============================================
-- REQUISITOS_DOCENTES: biblioteca de plantillas por condición laboral
-- Almacena plantillas descargables subidas por admin, agrupadas por
-- CONDICION_LABORAL (tipo de contrato) y CLASIFICACION (categoría libre).
-- El archivo subido siempre es una plantilla.
-- Unicidad por combinación (CONDICION_LABORAL + CLASIFICACION + NOMBRE).
-- ============================================

CREATE TABLE IF NOT EXISTS "REQUISITOS_DOCENTES" (
    "ID_REQUISITO" INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    "CONDICION_LABORAL" VARCHAR(20) NOT NULL
        CHECK ("CONDICION_LABORAL" IN ('CONTRATADO', 'EXTERNO', 'ORDINARIO')),
    "CLASIFICACION" VARCHAR(50) NOT NULL,
    "NOMBRE" VARCHAR(100) NOT NULL,
    "DESCRIPCION" TEXT,
    "OBLIGATORIO" BOOLEAN NOT NULL DEFAULT FALSE,
    -- Campos de archivo plantilla (subido a Supabase Storage, bucket 'postulaciones-adjuntos')
    "STORAGE_PATH" VARCHAR(500),
    "FILENAME" VARCHAR(255),
    "CONTENT_TYPE" VARCHAR(100),
    "TAMAÑO_BYTES" INTEGER,
    "FECHA_SUBIDA" TIMESTAMP NOT NULL DEFAULT NOW(),
    "ACTIVO" BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT "UQ_REQUISITOS_DOCENTES_COMBINACION"
        UNIQUE ("CONDICION_LABORAL", "CLASIFICACION", "NOMBRE")
);

CREATE INDEX IF NOT EXISTS "IDX_REQUISITOS_DOCENTES_CONDICION_CLASIFICACION"
    ON "REQUISITOS_DOCENTES" ("CONDICION_LABORAL", "CLASIFICACION");

CREATE INDEX IF NOT EXISTS "IDX_REQUISITOS_DOCENTES_ACTIVO"
    ON "REQUISITOS_DOCENTES" ("ACTIVO");

-- ============================================
-- POSTULACION_PLAZA: postulaciones a convocatoria_curso
-- Los adjuntos se almacenan en la tabla normalizada POSTULACION_ADJUNTOS.
-- CONDICION_LABORAL_SNAPSHOT: snapshot inmutable de la condición laboral del docente
-- al crear la postulación. Se usa para contextualizar los adjuntos sin reconsultar.
-- ============================================

CREATE TABLE IF NOT EXISTS "POSTULACION_PLAZA" (
    "ID_POSTULACION" INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    "ID_CONVOCATORIA_CURSO" INTEGER NOT NULL,
    "ID_PLAZA_DOCENTE" INTEGER,
    "ID_DOCENTE" INTEGER NOT NULL,
    "CONDICION_LABORAL_SNAPSHOT" VARCHAR(20),
    "FECHA_POSTULACION" TIMESTAMP NOT NULL DEFAULT NOW(),
    "ESTADO" VARCHAR(20) NOT NULL DEFAULT 'postulado',
    "ACEPTADO" BOOLEAN NOT NULL DEFAULT FALSE,
    "FECHA_ACEPTACION" TIMESTAMP,
    "FECHA_ENTREVISTA" TIMESTAMP,
    "ENTREVISTA_REALIZADA" BOOLEAN NOT NULL DEFAULT FALSE,
    "NOTA_ENTREVISTA" TEXT,
    "CONTRATO_FIRMADO" BOOLEAN NOT NULL DEFAULT FALSE,
    "FECHA_CONTRATO" DATE,
    "OBSERVACIONES" TEXT,
    "ACTIVO" BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT "CHK_POSTULACION_ESTADO"
    CHECK ("ESTADO" IN ('postulado','en_revision','entrevista','documentos','contratado','descartado')),
    CONSTRAINT "CHK_POSTULACION_ACEPTADO"
    CHECK ("ACEPTADO" = FALSE OR ("ACEPTADO" = TRUE AND "ESTADO" = 'contratado')),
    CONSTRAINT "FK_POSTULACION_CONVOCATORIA_CURSO"
    FOREIGN KEY ("ID_CONVOCATORIA_CURSO") REFERENCES "CONVOCATORIA_CURSO" ("ID_CONVOCATORIA_CURSO")
    ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "FK_POSTULACION_PLAZA"
    FOREIGN KEY ("ID_PLAZA_DOCENTE") REFERENCES "PLAZA_DOCENTE" ("ID_PLAZA_DOCENTE")
    ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "FK_POSTULACION_DOCENTE"
    FOREIGN KEY ("ID_DOCENTE") REFERENCES "DOCENTES" ("ID_DOCENTE")
    ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "UQ_POSTULACION_CONVOCATORIA_CURSO_DOCENTE" UNIQUE ("ID_CONVOCATORIA_CURSO","ID_DOCENTE")
);

CREATE UNIQUE INDEX IF NOT EXISTS "UQ_POSTULACION_PLAZA_ASIGNADA"
    ON "POSTULACION_PLAZA" ("ID_PLAZA_DOCENTE")
    WHERE "ID_PLAZA_DOCENTE" IS NOT NULL AND "ACTIVO" = TRUE;

CREATE INDEX IF NOT EXISTS "IDX_POSTULACION_CONVOCATORIA_CURSO"
    ON "POSTULACION_PLAZA" ("ID_CONVOCATORIA_CURSO");

CREATE INDEX IF NOT EXISTS "IDX_POSTULACION_PLAZA_DOCENTE"
    ON "POSTULACION_PLAZA" ("ID_DOCENTE");

CREATE INDEX IF NOT EXISTS "IDX_POSTULACION_PLAZA_ESTADO"
    ON "POSTULACION_PLAZA" ("ESTADO");

-- ============================================
-- POSTULACION_ADJUNTOS: documentos de postulación normalizados.
-- Una fila por archivo (requisito predefinido o extra).
-- Snapshot inmutable: NOMBRE, OBLIGATORIO, PLANTILLA_RUTA, PLANTILLA_FILENAME.
-- ARCHIVO_PATH = null significa pendiente de subir.
-- ============================================

CREATE TABLE IF NOT EXISTS "POSTULACION_ADJUNTOS" (
    "ID_ADJUNTO" INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    "ID_POSTULACION" INTEGER NOT NULL,
    "CLASIFICACION" VARCHAR(50) NOT NULL,
    "TIPO" VARCHAR(10) NOT NULL DEFAULT 'req'
        CHECK ("TIPO" IN ('req', 'ext')),
    "ID_REQUISITO" INTEGER,
    "NOMBRE" VARCHAR(200) NOT NULL,
    "OBLIGATORIO" BOOLEAN NOT NULL DEFAULT FALSE,
    "PLANTILLA_RUTA" VARCHAR(500),
    "PLANTILLA_FILENAME" VARCHAR(255),
    "ARCHIVO_PATH" VARCHAR(500),
    "ARCHIVO_FILENAME" VARCHAR(255),
    "ARCHIVO_CONTENT_TYPE" VARCHAR(100),
    "ARCHIVO_SIZE" INTEGER,
    "ARCHIVO_SUBIDO_EN" TIMESTAMP,
    "FECHA_CREACION" TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT "FK_ADJUNTO_POSTULACION"
    FOREIGN KEY ("ID_POSTULACION") REFERENCES "POSTULACION_PLAZA" ("ID_POSTULACION")
    ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE INDEX IF NOT EXISTS "IDX_ADJUNTO_POSTULACION"
    ON "POSTULACION_ADJUNTOS" ("ID_POSTULACION");

CREATE INDEX IF NOT EXISTS "IDX_ADJUNTO_CLASIFICACION"
    ON "POSTULACION_ADJUNTOS" ("CLASIFICACION");

CREATE INDEX IF NOT EXISTS "IDX_ADJUNTO_TIPO"
    ON "POSTULACION_ADJUNTOS" ("TIPO");

CREATE INDEX IF NOT EXISTS "IDX_ADJUNTO_OBLIGATORIO_PENDIENTE"
    ON "POSTULACION_ADJUNTOS" ("ID_POSTULACION")
    WHERE "OBLIGATORIO" = TRUE AND "ARCHIVO_PATH" IS NULL;


