-- ============================================

-- ELIMINACIÓN DE TABLAS (si existen)

DROP TABLE IF EXISTS "TIPO_CORREO_CUENTA_SEDE" CASCADE;
DROP TABLE IF EXISTS "CUENTAS_SMTP" CASCADE;
DROP TABLE IF EXISTS "PASSWORD_RESET_CODES" CASCADE;
DROP TABLE IF EXISTS "CORREOS" CASCADE;
DROP TABLE IF EXISTS "TIPOS_CORREO" CASCADE;
DROP TABLE IF EXISTS "CARRERAS" CASCADE;
DROP TABLE IF EXISTS "PERMISOS" CASCADE;
DROP TABLE IF EXISTS "ROLES" CASCADE;
DROP TABLE IF EXISTS "AULAS" CASCADE;
DROP TABLE IF EXISTS "DOCENTES" CASCADE;
DROP TABLE IF EXISTS "USUARIOS" CASCADE;
DROP TABLE IF EXISTS "AREAS" CASCADE;
DROP TABLE IF EXISTS "CURSOS" CASCADE;
DROP TABLE IF EXISTS "SEDES" CASCADE;

-- ============================================

-- CREACIÓN DE TABLAS

-- ============================================

-- Tabla SEDES

CREATE TABLE "SEDES" (
    "ID_SEDE" INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    "NOMBRE_SEDE" VARCHAR(50) NOT NULL UNIQUE,
    "CODIGO_SEDE" VARCHAR(10) NOT NULL UNIQUE,
    "ACTIVO" BOOLEAN NOT NULL DEFAULT TRUE
);
-- Tabla CURSOS

CREATE TABLE "CURSOS" (
    "ID_CURSO" INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    "CODIGO_CURSO" VARCHAR(30) NOT NULL,
    "NOMBRE_CURSO" VARCHAR(150) NOT NULL,
    "EJE_TEMATICO" VARCHAR(50) NOT NULL,
    "COLOR" VARCHAR(7) DEFAULT NULL,
    "ACTIVO" BOOLEAN NOT NULL DEFAULT TRUE
);
-- Índices de CURSOS (con IF NOT EXISTS)

CREATE INDEX IF NOT EXISTS "IDX_CURSOS_CODIGO_CURSO" ON "CURSOS" ("CODIGO_CURSO");
CREATE INDEX IF NOT EXISTS "IDX_CURSOS_EJE_TEMATICO"      ON "CURSOS" ("EJE_TEMATICO");
-- Tabla AREAS

CREATE TABLE "AREAS" (
    "ID_AREA" INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    "NOMBRE_AREA" VARCHAR(20) NOT NULL UNIQUE,
    "CODIGO_AREA" VARCHAR(20) NOT NULL UNIQUE,
    "ACTIVO" BOOLEAN NOT NULL DEFAULT TRUE
);
-- Tabla USUARIOS

CREATE TABLE "USUARIOS" (
    "ID_USUARIO" INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    "DNI" VARCHAR(8) UNIQUE,
    "APELLIDOS" VARCHAR(100) NOT NULL,
    "NOMBRES" VARCHAR(100) NOT NULL,
    "FECHA_NACIMIENTO" DATE,
    "SEXO" VARCHAR(20),
    "TELEFONO" VARCHAR(20),
    "EMAIL" VARCHAR(100) UNIQUE,
    "DIRECCION" VARCHAR(200),
    "SUPABASE_UID" UUID UNIQUE,
    "PASSWORD_HASH" VARCHAR(255) DEFAULT NULL,
    "ID_ROLES" INTEGER[] NOT NULL DEFAULT '{}',
    "ACTIVO" BOOLEAN NOT NULL DEFAULT TRUE,
    "REQUIERE_CAMBIO_PASSWORD" BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT "CHK_DNI_USUARIO" CHECK ("DNI" IS NULL OR (LENGTH("DNI") = 8 AND "DNI" ~ '^[0-9]+$'))
);

CREATE INDEX IF NOT EXISTS "IDX_USUARIOS_DNI" ON "USUARIOS" ("DNI");

-- Tabla DOCENTES

CREATE TABLE "DOCENTES" (
    "ID_DOCENTE" INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    "ID_USUARIO" INTEGER NOT NULL UNIQUE,
    "RUC" VARCHAR(20) NOT NULL,
    "CONDICION_LABORAL" VARCHAR(20) NOT NULL,
    "ACTIVO" BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT "FK_DOCENTES_USUARIO" FOREIGN KEY ("ID_USUARIO")
    REFERENCES "USUARIOS" ("ID_USUARIO")
    ON DELETE CASCADE
    ON UPDATE CASCADE,
    CONSTRAINT "CHK_DOCENTES_CONDICION_LABORAL"
    CHECK ("CONDICION_LABORAL" IN ('CONTRATADO','EXTERNO','ORDINARIO'))
);
-- NOTA: ESTUDIANTES eliminado; USUARIOS es ahora la identidad canonica

-- Tabla AULAS

CREATE TABLE "AULAS" (
    "ID_AULA" INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    "ID_SEDE" INTEGER NOT NULL,
    "NOMBRE_AULA" VARCHAR(50) NOT NULL,
    "CODIGO_AULA" VARCHAR(20) NOT NULL,
    "UBICACION" VARCHAR(100),
    "TIPO" VARCHAR(20) NOT NULL DEFAULT 'presencial',
    "ENLACE_VIRTUAL" VARCHAR(255),
    "CAPACIDAD" INTEGER,
    "ACTIVO" BOOLEAN DEFAULT TRUE,
    CONSTRAINT "CHK_TIPO_AULA" CHECK ("TIPO" IN ('presencial', 'virtual')),
    CONSTRAINT "UQ_AULA_SEDE" UNIQUE ("ID_SEDE", "NOMBRE_AULA"),
    CONSTRAINT "FK_AULAS_SEDE" FOREIGN KEY ("ID_SEDE")
    REFERENCES "SEDES" ("ID_SEDE")
    ON DELETE RESTRICT
    ON UPDATE CASCADE
);


-- Tabla ROLES

CREATE TABLE "ROLES" (
    "ID_ROL" INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    "NOMBRE_ROL" VARCHAR(50) NOT NULL UNIQUE,
    "DESCRIPCION" VARCHAR(200),
    "NIVEL_ACCESO" INTEGER NOT NULL DEFAULT 1,
    "ACTIVO" BOOLEAN NOT NULL DEFAULT TRUE,
    "ES_SISTEMA" BOOLEAN NOT NULL DEFAULT FALSE,
    "ID_PERMISOS" INTEGER[] NOT NULL DEFAULT '{}'
);

CREATE INDEX IF NOT EXISTS "IDX_ROLES_NOMBRE" ON "ROLES" ("NOMBRE_ROL");

-- Tabla PERMISOS

CREATE TABLE "PERMISOS" (
    "ID_PERMISO" INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    "RECURSO" VARCHAR(50) NOT NULL,
    "ACCION" VARCHAR(50) NOT NULL,
    "DESCRIPCION" VARCHAR(200),
    UNIQUE ("RECURSO", "ACCION"),
    "ACTIVO" BOOLEAN NOT NULL DEFAULT TRUE
);

-- Tabla CARRERAS

CREATE TABLE "CARRERAS" (
    "ID_CARRERA" INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    "NOMBRE_CARRERA" VARCHAR(150) NOT NULL,
    "CODIGO_CARRERA" VARCHAR(20) NOT NULL UNIQUE,
    "ID_AREA" INTEGER NOT NULL,
    "ID_SEDES" INTEGER[] NOT NULL DEFAULT '{}',
    "ACTIVO" BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT "FK_CARRERAS_AREA"
    FOREIGN KEY ("ID_AREA") REFERENCES "AREAS" ("ID_AREA")
    ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE INDEX IF NOT EXISTS "IDX_CARRERAS_AREA" ON "CARRERAS" ("ID_AREA");

CREATE OR REPLACE FUNCTION fn_array_int_sin_duplicados(arr INTEGER[])
RETURNS BOOLEAN AS $$
BEGIN
  RETURN arr IS NULL OR (
    SELECT COUNT(*) FROM unnest(arr) AS u
  ) = (
    SELECT COUNT(DISTINCT u) FROM unnest(arr) AS u
  );
END;
$$ LANGUAGE plpgsql IMMUTABLE;


ALTER TABLE "ROLES"
  ADD CONSTRAINT "CHK_ROLES_ID_PERMISOS_UNICOS"
  CHECK (fn_array_int_sin_duplicados("ID_PERMISOS"));

ALTER TABLE "USUARIOS"
  ADD CONSTRAINT "CHK_USUARIOS_ID_ROLES_UNICOS"
  CHECK (fn_array_int_sin_duplicados("ID_ROLES"));

ALTER TABLE "CARRERAS"
  ADD CONSTRAINT "CHK_CARRERAS_ID_SEDES_UNICOS"
  CHECK (fn_array_int_sin_duplicados("ID_SEDES"));

CREATE INDEX IF NOT EXISTS "IDX_ROLES_ID_PERMISOS" ON "ROLES" USING GIN ("ID_PERMISOS");
CREATE INDEX IF NOT EXISTS "IDX_USUARIOS_ID_ROLES" ON "USUARIOS" USING GIN ("ID_ROLES");

CREATE INDEX IF NOT EXISTS "IDX_CARRERAS_ID_SEDES" ON "CARRERAS" USING GIN ("ID_SEDES");

-- Tabla TIPOS_CORREO

CREATE TABLE "TIPOS_CORREO" (
    "ID_TIPO" INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    "NOMBRE_TIPO" VARCHAR(50) NOT NULL UNIQUE,
    "DESCRIPCION" VARCHAR(200),
    "ENVIO_AUTOMATICO" BOOLEAN NOT NULL DEFAULT FALSE,
    "MULTI_USUARIO" BOOLEAN NOT NULL DEFAULT FALSE,
    "ID_CUENTA" INTEGER,
    "ACTIVO" BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT "CHK_TIPOS_NOMBRE" CHECK ("NOMBRE_TIPO" ~ '^[a-z_]+$')
);

-- Tabla CORREOS

CREATE TABLE "CORREOS" (
    "ID_CORREO" INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    "TIPO" VARCHAR(50) NOT NULL,
    "ID_USUARIOS" INTEGER[] NOT NULL DEFAULT '{}',
    "DESTINATARIOS" TEXT[] NOT NULL DEFAULT '{}',
    "CC" TEXT[] DEFAULT '{}',
    "BCC" TEXT[] DEFAULT '{}',
    "ASUNTO" VARCHAR(200) NOT NULL,
    "CUERPO_HTML" TEXT NOT NULL,
    "CUERPO_TEXTO" TEXT,
    "ADJUNTOS" JSONB DEFAULT '[]',
    "MESSAGE_ID" VARCHAR(255),
    "ESTADO" VARCHAR(20) NOT NULL DEFAULT 'pendiente',
    "ERROR" TEXT,
    "PRIORIDAD" VARCHAR(20) NOT NULL DEFAULT 'normal',
    "FECHA_PROGRAMADA" TIMESTAMP,
    "INTENTOS" INTEGER NOT NULL DEFAULT 0,
    "METADATOS" JSONB DEFAULT '{}',
    "CREADO_EN" TIMESTAMP NOT NULL DEFAULT NOW(),
    "ENVIADO_EN" TIMESTAMP,
    "CREADO_POR" VARCHAR(100),
    "ENVIO_AUTOMATICO" BOOLEAN NOT NULL DEFAULT FALSE,
    "BLOQUEADO" BOOLEAN NOT NULL DEFAULT FALSE,
    "PERSONALIZADO" BOOLEAN NOT NULL DEFAULT FALSE,
    "OBSERVACIONES" TEXT,
    "REMITENTE" VARCHAR(255)
);

CREATE INDEX IF NOT EXISTS "IDX_CORREOS_TIPO" ON "CORREOS" ("TIPO");
CREATE INDEX IF NOT EXISTS "IDX_CORREOS_ESTADO" ON "CORREOS" ("ESTADO");
CREATE INDEX IF NOT EXISTS "IDX_CORREOS_USUARIOS" ON "CORREOS" USING GIN ("ID_USUARIOS");
CREATE INDEX IF NOT EXISTS "IDX_CORREOS_PRIORIDAD" ON "CORREOS" ("PRIORIDAD");

ALTER TABLE "CORREOS" ADD CONSTRAINT "CHK_CORREOS_ESTADO"
  CHECK ("ESTADO" IN ('pendiente', 'enviado', 'cancelado', 'fallido'));

ALTER TABLE "CORREOS" ADD CONSTRAINT "CHK_CORREOS_PRIORIDAD"
  CHECK ("PRIORIDAD" IN ('alta', 'normal', 'baja'));

ALTER TABLE "CORREOS" ADD CONSTRAINT "CHK_CORREOS_DESTINATARIOS"
  CHECK (array_length("DESTINATARIOS", 1) > 0);

ALTER TABLE "CORREOS" ADD CONSTRAINT "CHK_CORREOS_BLOQUEO"
  CHECK (NOT ("BLOQUEADO" = TRUE AND "ESTADO" = 'pendiente'));

-- Tabla PASSWORD_RESET_CODES

CREATE TABLE "PASSWORD_RESET_CODES" (
    "ID_RESET" INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    "ID_CORREO" INTEGER,
    "DNI" VARCHAR(8) NOT NULL,
    "EMAIL" VARCHAR(100) NOT NULL,
    "CODIGO" VARCHAR(6) NOT NULL,
    "CREADO_EN" TIMESTAMP NOT NULL DEFAULT NOW(),
    "EXPIRA_EN" TIMESTAMP NOT NULL,
    "USADO" BOOLEAN NOT NULL DEFAULT FALSE,
    "FECHA_USO" TIMESTAMP,
    CONSTRAINT "FK_RESET_CORREO" FOREIGN KEY ("ID_CORREO")
        REFERENCES "CORREOS" ("ID_CORREO")
        ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE INDEX IF NOT EXISTS "IDX_RESET_DNI" ON "PASSWORD_RESET_CODES" ("DNI");
CREATE INDEX IF NOT EXISTS "IDX_RESET_CODIGO" ON "PASSWORD_RESET_CODES" ("CODIGO");
CREATE INDEX IF NOT EXISTS "IDX_RESET_EXPIRA" ON "PASSWORD_RESET_CODES" ("EXPIRA_EN");
CREATE INDEX IF NOT EXISTS "IDX_RESET_VERIFY" ON "PASSWORD_RESET_CODES" ("DNI", "USADO", "EXPIRA_EN");

ALTER TABLE "PASSWORD_RESET_CODES" ADD CONSTRAINT "CHK_RESET_CODIGO"
  CHECK ("CODIGO" ~ '^[0-9]{6}$');


-- Tabla CUENTAS_SMTP

CREATE TABLE "CUENTAS_SMTP" (
    "ID_CUENTA" INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    "NOMBRE_CUENTA" VARCHAR(100) NOT NULL,
    "SMTP_HOST" VARCHAR(100) NOT NULL,
    "SMTP_PORT" INTEGER NOT NULL DEFAULT 587,
    "SMTP_USER" VARCHAR(100) NOT NULL,
    "SMTP_PASS_ENCRYPTED" TEXT NOT NULL,
    "SMTP_PASS_IV" VARCHAR(50) NOT NULL,
    "SMTP_PASS_TAG" VARCHAR(100) NOT NULL,
    "ACTIVO" BOOLEAN NOT NULL DEFAULT TRUE,
    "CREADO_EN" TIMESTAMP NOT NULL DEFAULT NOW()
);

ALTER TABLE "TIPOS_CORREO"
    ADD CONSTRAINT "FK_TIPOS_CORREO_CUENTA"
    FOREIGN KEY ("ID_CUENTA") REFERENCES "CUENTAS_SMTP" ("ID_CUENTA")
    ON DELETE SET NULL ON UPDATE CASCADE;



